### ISSUE TITLE
how many gpus use?

### ISSUE THREAD

**Issue by cliuxinxin** [NVIDIA/tacotron2#101]
I tried on my 1080ti . Inference the example about 1s use at least 3s.If I add gpus, this time will reduce or not?

**Comment by rafaelvalle** [comment]
Inference is approximately 6.6x real-time using FP32 on a Volta 100.

**Comment by cliuxinxin** [comment]
@rafaelvalle  thank you for your replay

**Comment by cliuxinxin** [comment]
@rafaelvalle FP32 use the defuault code in inference or something will change. I am glad to try the inference time use the 1080ti and report back.

**Comment by rafaelvalle** [comment]
Please do.

**Comment by cliuxinxin** [comment]
@rafaelvalle 
this is the loading code
![image](https://user-images.githubusercontent.com/6162238/49556076-31e1c100-f93d-11e8-88c6-1c527a2bedc5.png)
card info
![image](https://user-images.githubusercontent.com/6162238/49556095-4756eb00-f93d-11e8-8b71-beae3c7b5996.png)
infer the spectruam
![image](https://user-images.githubusercontent.com/6162238/49556141-884eff80-f93d-11e8-8e6e-c569eebca30e.png)
infer the wav
![image](https://user-images.githubusercontent.com/6162238/49556172-a452a100-f93d-11e8-9b4d-42c3040b7c2a.png)
wav length
![image](https://user-images.githubusercontent.com/6162238/49556212-c64c2380-f93d-11e8-8834-603754dba056.png)
about 4s infer 1s. This is my result on 1080ti

**Comment by rafaelvalle** [comment]
Two suggestions:
1) Increase the size of your predicted mel to be around 10 seconds
2) Convert waveglow to FP16. This one-liner probably works
```waveglow = waveglow.half()```

**Comment by cliuxinxin** [comment]
@rafaelvalle 
extend to 10s and use half
![image](https://user-images.githubusercontent.com/6162238/49563541-459c2000-f95b-11e8-972a-4f6dbc0351ce.png)
now get error

> ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-a245159cec35> in <module>()
      3 start = time()
      4 with torch.no_grad():
----> 5     audio = waveglow.infer(mel_outputs_postnet, sigma=0.666)
      6 ipd.Audio(audio[0].data.cpu().numpy(), rate=hparams.sampling_rate)
      7 # stop = time()

~/exp/tacotron2/waveglow/glow_old.py in infer(self, spect, sigma)
    171 
    172     def infer(self, spect, sigma=1.0):
--> 173         spect = self.upsample(spect)
    174         # trim conv artifacts. maybe pad spec to kernel multiple
    175         time_cutoff = self.upsample.kernel_size[0] - self.upsample.stride[0]

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py in forward(self, input, output_size)
    584         return F.conv_transpose1d(
    585             input, self.weight, self.bias, self.stride, self.padding,
--> 586             output_padding, self.groups, self.dilation)
    587 
    588 

RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

I thought the glow use fp16 and the tacotron not. so I  change the input as 
![image](https://user-images.githubusercontent.com/6162238/49563693-d7a42880-f95b-11e8-9d45-e484cb29256b.png)

I got another error
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-1d05ecdfac8a> in <module>()
      3 start = time()
      4 with torch.no_grad():
----> 5     audio = waveglow.infer(mel_outputs_postnet.half(), sigma=0.666)
      6 ipd.Audio(audio[0].data.cpu().numpy(), rate=hparams.sampling_rate)
      7 # stop = time()

~/exp/tacotron2/waveglow/glow_old.py in infer(self, spect, sigma)
    208                 audio = torch.cat([audio_1, audio[:,n_half:,:]], 1)
    209 
--> 210             audio = self.convinv[k](audio, reverse=True)
    211 
    212             if k%4 == 0 and k > 0:

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/exp/tacotron2/waveglow/glow.py in forward(self, z, reverse)
     89             if not hasattr(self, 'W_inverse'):
     90                 # Reverse computation
---> 91                 W_inverse = W.inverse()


     92                 W_inverse = Variable(W_inverse[..., None])
     93                 if z.type() == 'torch.cuda.HalfTensor':

RuntimeError: _th_getri_single is not implemented for type torch.cuda.HalfTensor

it seems some function doest have half tensor method.
After all I tried 10s
![image](https://user-images.githubusercontent.com/6162238/49563820-54cf9d80-f95c-11e8-919a-163a530c11fe.png)
![image](https://user-images.githubusercontent.com/6162238/49563845-7466c600-f95c-11e8-951e-ebb15af8aeed.png)
it seems 3s for 1s

**Comment by rafaelvalle** [comment]
That's because the inverse() only exists for FP32 matrices. 
Use this new code to convert WaveGlow to FP16. 
```
waveglow.half()
    for k in waveglow.convinv:
        k.float()
```

**Comment by cliuxinxin** [comment]
@rafaelvalle 
first , let us listen to the normal wav , 3s generate 1s

[normal.wav.zip](https://github.com/NVIDIA/tacotron2/files/2651888/normal.wav.zip)

then sound of silence
[fp16.wav.zip](https://github.com/NVIDIA/tacotron2/files/2651892/fp16.wav.zip)
change to the fp16
![image](https://user-images.githubusercontent.com/6162238/49565163-3ae48980-f961-11e8-841f-2b06994138e4.png)
this time no more fp16 error
and half time compare to the fp32 , but get the sound of silence
![image](https://user-images.githubusercontent.com/6162238/49565300-ae869680-f961-11e8-81b6-9c379840ed2a.png)

**Comment by rafaelvalle** [comment]
Try restarting the notebook. The notebook on master with fp16 works fine.

**Comment by cliuxinxin** [comment]
for safe , I  clone the entire code base
![image](https://user-images.githubusercontent.com/6162238/49567462-b6960480-f968-11e8-8c7c-861341b65a6c.png)
![image](https://user-images.githubusercontent.com/6162238/49567470-bbf34f00-f968-11e8-8eae-93c1f9acf266.png)
but still get sound of silence. It's a strange world. But compare to the wavenet. The speed is still faster. If you @rafaelvalle have more interest in this silence issue . I'd happy to give you the  notebook ip (privately) to try it out. 
Thank you for your time.

**Comment by mrgloom** [comment]
@cliuxinxin 
You can use `%%time` in notebook cell to measure execution time.

`waveglow.half()` produce error:
```
~/external_projects/text-to-speech/NVIDIA/tacotron2/waveglow/denoiser.py in __init__(self, waveglow, filter_length, n_overlap, win_length, mode)
     18                 (1, 80, 88),
     19                 dtype=waveglow.upsample.weight.dtype,
---> 20                 device=waveglow.upsample.weight.device)
     21         elif mode == 'normal':
     22             mel_input = torch.randn(

RuntimeError: _th_zero_ is not implemented for type torch.HalfTensor
```
Maybe because I'm doing inference on CPU?

**Comment by ErfolgreichCharismatisch** [comment]
Tutorial: Training on GPU with Colab, Inference with CPU on Server [here](https://github.com/NVIDIA/tacotron2/issues/467).
