### ISSUE TITLE
inference.ipynb not working with pre-trained model.

### ISSUE THREAD

**Issue by TesseractCat** [NVIDIA/tacotron2#103]
When I run inference.ipynb I get this error:
```
model.load_state_dict({k.replace('module.',''):v for k,v in state_dict_var.items()})
  File "C:\Users\tesseractcat\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron2:
        size mismatch for embedding.weight: copying a param with shape torch.Size([148, 512]) from checkpoint, the shape in current model is torch.Size([149, 512]).
        size mismatch for decoder.attention_rnn.weight_ih: copying a param with shape torch.Size([4096, 768]) from checkpoint, the shape in current model is torch.Size([4096, 1536]).
        size mismatch for decoder.decoder_rnn.weight_ih: copying a param with shape torch.Size([4096, 1536]) from checkpoint, the shape in current model is torch.Size([4096, 768]).
```
This is using the pretrained model provided (tacotron2_statedict.pt)

**Comment by TesseractCat** [comment]
I accidentally downloaded an old version of the repository, so I will close this issue.

**Comment by jiangyangbo** [comment]
can provide   the newest tacotron2 model for inference?

**Comment by AnkurDebnath35** [comment]
`
RuntimeError: Error(s) in loading state_dict for Tacotron2:
	size mismatch for embedding.weight: copying a param with shape torch.Size([148, 512]) from checkpoint, the shape in current model is torch.Size([151, 512]).
`
I got this error while inferencing from tacotron2_statedict.pt . Please help.

**Comment by CookiePPP** [comment]
@AnkurDebnath35 
Can you check you're using the original [symbols.py](https://github.com/NVIDIA/tacotron2/blob/master/text/symbols.py)?

**Comment by AnkurDebnath35** [comment]
@CookiePPP I did, and its the original one only.

**Comment by CookiePPP** [comment]
@AnkurDebnath35 

If you are sure it's the original, then either your `n_symbols` in [hparams](https://github.com/NVIDIA/tacotron2/blob/master/hparams.py#L47) or [cmudict](https://github.com/NVIDIA/tacotron2/blob/master/text/cmudict.py#L6#L14) `valid symbols` are wrong.
