### ISSUE TITLE
Training for other languages

### ISSUE THREAD

**Issue by chrizandr** [NVIDIA/tacotron2#106]
If we want to try and train this model for languages other than English, with non-roman characters, will it be enough to modify the text processing to generate appropriate sequences for the language without any other modifications?

Is there some other processing done on the input/target values that might be language specific?

**Comment by rafaelvalle** [comment]
Yes, it would be enough to substitute the symbols on the file below with the characters specific to the language at hand.
https://github.com/NVIDIA/tacotron2/blob/master/text/symbols.py
