### ISSUE TITLE
inferencing in FP16 results in silence

### ISSUE THREAD

**Issue by abuvaneswari** [NVIDIA/tacotron2#107]
Hello,

Using Pytorch 1.0 dev, Python 3.6

Utilized your pretrained models for tacotron2 and waveglow. Ran inferencing.ipynb. The resulting audio is a complete silence. Whereas, when I utilize griffin-lim for inverting the same mel output, I get somewhat acceptable audio.

Griffin-lim inversion code:
`taco_stft = TacotronSTFT(
    hparams.filter_length, hparams.hop_length, hparams.win_length, 
    sampling_rate=hparams.sampling_rate)

mel_decompress = taco_stft.spectral_de_normalize(mel_outputs_postnet)
mel_decompress = mel_decompress.transpose(1, 2).data.cpu()
spec_from_mel_scaling = 1000
spec_from_mel = torch.mm(mel_decompress[0], taco_stft.mel_basis)
spec_from_mel = spec_from_mel.transpose(0, 1).unsqueeze(0)
spec_from_mel = spec_from_mel * spec_from_mel_scaling

waveform = griffin_lim(torch.autograd.Variable(spec_from_mel[:, :, :-1]), 
                       taco_stft.stft_fn, 60)`

Audio files:
[t2-synth-files.gl.wg.zip](https://github.com/NVIDIA/tacotron2/files/2660227/t2-synth-files.gl.wg.zip)

**Comment by rafaelvalle** [comment]
Thank you for reporting. We are investigating.
Use FP32 inference meanwhile.

**Comment by rafaelvalle** [comment]
This issue should be fixed.
