### ISSUE TITLE
Memory Requirement

### ISSUE THREAD

**Issue by macarbonneau** [NVIDIA/tacotron2#11]
Hi!
    Thanks for the code! I tried to run train.py, but got a memory error. I have a 1080Ti with 11Gb. What hardware do you use? Do you know what are the memory requirements?

Thank you!

**Comment by rafaelvalle** [comment]
Watch your memory foot-print and adapt batch size accordingly. Probably something around 32 gb works fine for the 1080Ti

To watch your memory footprint use on the cli: `watch -n .1 nvidia-smi`
