### ISSUE TITLE
waveglow.infer CUDA out of memory

### ISSUE THREAD

**Issue by ibraheemalkilanny** [NVIDIA/tacotron2#114]
Trying to infer from published pretrained models, I am getting CUDA out of memory

How can I infer with lower GPU memory ?

**Comment by rafaelvalle** [comment]
Try using smaller mel chunks with some overlap. Then crossfade the audio

**Comment by Mr-DDDAlKilanny** [comment]
Thanks. I think this solution would lead sound to be low quality due to multiple short chunks being combined. Is there something better instead? Thanks again
