### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by zfallahnejad** [NVIDIA/tacotron2#115]
I want to train a simple model for my dataset (non-English). You can see my code in this notebook
 [https://colab.research.google.com/drive/1Arso-XWcklFVma5EdswFQn9XTWyV6xMu](url)
But, there are no '.pt' file in my output_directory.  
Can you tell me how can I generate these two pt files which you mentioned in `Inference` section?

**Comment by rafaelvalle** [comment]
The .pt files with the model, optimizer states, etc, are saved during checkpoint in training.
