### ISSUE TITLE
Missing @staticmethod in loss_scaler.py

### ISSUE THREAD

**Issue by muximus3** [NVIDIA/tacotron2#118]
```python
def _has_inf_or_nan(x):
    return False
```
this method looks like a static method in both `LossScaler` and `DynamicLossScaler` class, but without `@statticmethod`.

**Comment by rafaelvalle** [comment]
Thank you. We're soon replacing these with the [AMP](https://github.com/NVIDIA/apex/tree/master/apex/amp) library.
