### ISSUE TITLE
Audio seems to be breaking in the middle of the sentence

### ISSUE THREAD

**Issue by kushukla** [NVIDIA/tacotron2#119]
Is there any limit on the number of characters it can synthesis? I used the pretrained network and tried with following text, but it seems the audio is getting chopped off while speaking "**Lampung**".

 "On 22 December 2018, a tsunami that followed an eruption and partial collapse of the Anak Krakatau volcano in the Sunda Strait struck coastal regions of Banten Province and **Lampung** Province, Indonesia."

**Comment by rishikksh20** [comment]
I am also facing same problem.

**Comment by rafaelvalle** [comment]
You probably need to change max_decoder_steps. 
Something like: tacotron.decoder.max_decoder_steps = 8000
https://github.com/NVIDIA/tacotron2/blob/master/hparams.py#L58

**Comment by rishikksh20** [comment]
@rafaelvalle thanks 👍
