### ISSUE TITLE
How much dataset is needed at least to train on your version?

### ISSUE THREAD

**Issue by begeekmyfriend** [NVIDIA/tacotron2#12]
I find that different versions have different quantities of dataset needed to train into convergence https://github.com/Rayhane-mamah/Tacotron-2/issues/35. I wonder how much is the least on your implementation?

**Comment by rafaelvalle** [comment]
We've been able to train with datasets of ~10h. With smaller datasets, data augmentation, e.g. using different segments of the same file, and possibly regularization can help if the model is not generalizing...

**Comment by begeekmyfriend** [comment]
Well, actually I am comparing two projects of Ito's and Mamah's to find out the key modification that would decide the quantity of dataset. I will make series of modifications step by step to make Ito's training into convergence and Mamah's into unconvergence on the same 10h length dataset. Just as Mamah said, it must be one of life's mysteries.

**Comment by rafaelvalle** [comment]
Thank you for doing this and please share your conclusions with the TTS community on these repos. In addition to model architecture, parameters and weight initialization, also make sure you take a look at differences in data pre-processing, scaling wav by max value, etc.

**Comment by begeekmyfriend** [comment]
I am glad to say I have transplanted some code from Rayhane Mamah's version into Keith Ito's one and it can get to convergence on small dataset (10h) within 8K steps. I will release my fork in several days since I want to find the way in minimal modification. I will notify you as well as Keith Ito at that time. But I think I can show some clues about the modification that the architecture seems a little different with Keith Ito's one https://github.com/Rayhane-mamah/Tacotron-2/issues/4#issuecomment-375676828. The `AttentionWrapper` class in Tensorflow is inappropriate for Tacotron model since the query of attention should be the hidden states of 2-layer decoder LSTM while in `AttentionWrapper` the default query is set as the hidden state of extra wrapped attention RNN. The attention RNN is redundant because it does the same thing that decoder LSTM does. Moreover the architecture mentioned in Tacotron paper shows that the query should be the hidden states of decoder LSTM. That is why Rayhane Mamah substitutes [TacotronDecoderCell](https://github.com/Rayhane-mamah/Tacotron-2/blob/master/tacotron/models/Architecture_wrappers.py#L72) for AttentionWrapper that can help get to convergence.

**Comment by rafaelvalle** [comment]
Thanks for sharing these! We'll do some comparisons and update this repo in accordingly.

**Comment by begeekmyfriend** [comment]
Two more points:
First, expand the range of distribution of mel samples. [As we can see](https://github.com/Rayhane-mamah/Tacotron-2/blob/master/hparams.py#L31-L32) in https://github.com/Rayhane-mamah/Tacotron-2/issues/18#issuecomment-382637788, Rayhane expanded the range of mel points and make the distribution symmetric. That is important for convergence which he did not say.
Second, use cumulative attention states (aka. cumulative alignments) for location states instead of previous state only. That is also an indispensable thing for small dataset convergence.
Maybe there are missing points to say. I am still watching the results until the modification to be released.

**Comment by rafaelvalle** [comment]
Thanks for sharing these, Leo. While you do the experiments, it would be great if you could also annotate how important each of these things are.

**Comment by rafaelvalle** [comment]
Thanks a lot for doing this work, @begeekmyfriend. Are you interested in putting a PR with this modifications to this repo?

**Comment by rafaelvalle** [comment]
@begeekmyfriend please pull from the branch and let us know what your convergence time is
It attends to the full mel instead of the prenet drop out mel: this should increase convergence time considerably.
https://github.com/NVIDIA/tacotron2/tree/attention_full_mel

**Comment by rafaelvalle** [comment]
Closing this issue given that in our implementation attending to the decoder's output instead of the drop'ed out mels produces the same effect.
