### ISSUE TITLE
Capital letters in input alphabet

### ISSUE THREAD

**Issue by szcom** [NVIDIA/tacotron2#122]
Why capital letters are part of the input alphabet and affect the size of embedding layer if input text is always lowcase()'ed ?

Here is the alphabet:
https://github.com/NVIDIA/tacotron2/blob/master/text/symbols.py#L12

And here is the english cleaner:
https://github.com/NVIDIA/tacotron2/blob/master/text/cleaners.py#L86

**Comment by rafaelvalle** [comment]
You can train with both uppercase and lowercase characters by changing the cleaners.
