### ISSUE TITLE
Can this do TTS with pre-trained models instead of training for a week? Where does your Tacotron 2 model go?

### ISSUE THREAD

**Issue by MotorCityCobra** [NVIDIA/tacotron2#123]
I see this section in the ReadMe that says...

Inference demo
Download our published Tacotron 2 model
Download our published WaveGlow model
jupyter notebook --ip=127.0.0.1 --port=31337
Load inference.ipynb

I have the inference.ipynb notebook open.  
The waveglow model 'waveglow_old.pt' is loaded and in place.
All dependencies are installed okay. I just don't know where to put the tacotron2_statedict.pt model.  
I tried just storing it as 'model' several different ways. One example here. 

    nv_md = '/path/to/the/tacotron2_statedict.pt'
    model = load_model(hparams)
    model.load_state_dict(torch.load(nv_md))['state_dict']
    _ = model.eval()  

returns...

    RuntimeError: Error(s) in loading state_dict for Tacotron2:
	Missing key(s) in state_dict: "embedding.weight", "encoder.convolutions.0.0.conv.weight", "encoder.convolutions.0.0.conv.bias", "encoder.convolutions.0.1.weight", etc. <error goes on like this listing an entire model>.

BONUS Question: Why is every line repeated in the LJ Speech dataset csv? I'm working on a dataset of my own and wonder if this is required or if repeating it would be repeating a mistake.

**Comment by rafaelvalle** [comment]
It looks like the model given by `load_model` does not have the same keys/layers as the model from `nv_md`
