### ISSUE TITLE
How to get the max wav value?

### ISSUE THREAD

**Issue by WillQuCD** [NVIDIA/tacotron2#126]
Thanks for the contribution! 
I found the default max wav value in hparams is 32768.0.
Is this a  empirical value? If not, how can I get this value for my own dataset?
Also, how can I get the value of mel_fmin and mel_fmax?

Thanks!

**Comment by a-mushroom** [comment]
One wav point store in 2 bytes, 32768 is the max value of 2 bytes (2^15).

**Comment by WillQuCD** [comment]
Oh, I see. Thanks.
In term of value of mel_fmin and mel_fmax, could you explain more? I am not a speech guy.
Why do we need limit the mel values?
