### ISSUE TITLE
Is it possible to learn good spectrogram representation without good attention alignment?

### ISSUE THREAD

**Issue by WillQuCD** [NVIDIA/tacotron2#127]

**Comment by WillQuCD** [comment]
I use my dataset (500,000 sentences and each one is around 1s). 
It seems the model has learned good spectrogram after 56000 iterations but with poor attention alignment.
Is this result reasonable? Is it possible to synthesis comprehensible speech in this case?
Thanks!

![fireshot capture 1 - tensorboard - http___127 0 1 1_8008_](https://user-images.githubusercontent.com/28244700/51029965-3fbbdf00-1598-11e9-9694-d34191dbde43.png)

**Comment by prajwalkr** [comment]
Were you able to achieve good alignment? If so, at what epoch / iteration did you achieve it?
