### ISSUE TITLE
Zoneout

### ISSUE THREAD

**Issue by fatchord** [NVIDIA/tacotron2#13]
Hi, great repo and many thanks for putting your work up here for everyone.

One thing I just wanted to mention - I had a quick look at your code and it doesn't look like there is zoneout regularisation on the lstm decoders. Do you plan on adding it or indeed perhaps I missed it when I read the code?

**Comment by rafaelvalle** [comment]
Thank you for your kind words. Yes, this repo does not have Zoneout and we would possibly add it if there's an pull request adding this feature.
