### ISSUE TITLE
Trying to train on additional wavs I added, getting an out of range error

### ISSUE THREAD

**Issue by MotorCityCobra** [NVIDIA/tacotron2#132]
I've carefully added M-Ailabs female english spoken voices as wav files and created txt and csv files in the same format as the ljs set.  
I'm not sure what this error is telling me needs to be changed. I tried changing more values than just the txt paths in hparams.py. No luck.  
There are about 12,000 additional wav files. It never seems to grab an ljs wav AND THEN throw an error. This error always comes up so I wonder why it's not taking the len() of the files and working.

$ python train.py --output_directory=/home/eagle/p6/tacotron2/all_female/outdir/ --log_directory=logdir
FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
Epoch: 0
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 205, in train
    for i, batch in enumerate(train_loader):
  File "/home/eagle/whale/whale/lib/python3.6/site-packages/torch-1.0.0-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/eagle/whale/whale/lib/python3.6/site-packages/torch-1.0.0-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/eagle/whale/whale/lib/python3.6/site-packages/torch-1.0.0-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/eagle/whale/whale/lib/python3.6/site-packages/torch-1.0.0-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/eagle/p6/tacotron2/data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/home/eagle/p6/tacotron2/data_utils.py", line 34, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/home/eagle/p6/tacotron2/data_utils.py", line 42, in get_mel
    sampling_rate, self.stft.sampling_rate))
IndexError: tuple index out of range

**Comment by MotorCityCobra** [comment]
Figured it out. Sampling rate of my new wavs were out of range just like the error said.
Used librosa to change and wavio to change.

y, s = librosa.load(wav_file, sr=22050)
wavio.write(wav_file, y, rate, sampwidth=2)

Note that you want a bitrate of 16 so use sampwidth of 2 as above.

**Comment by WillQuCD** [comment]
@MotorCityCobra Why don't change the sampling_rate=22050 in hparams.py?

**Comment by MotorCityCobra** [comment]
@WillQuCD

Because I'm using a blend of three datasets. (All about 12 to 15 k utterances).  
The LJ dataset is originally in 22050 and M-AILABS wavs were something else.
Fast forward weeks later and I find the M-AILABS had 0.5 secs silence before and after that needed removed.  
I'm training now and I'm at 53000 iterations.
Not sure if it's going to work out yet.

**Comment by WillQuCD** [comment]
@MotorCityCobra 
"We have found that it is easier for the model to learn attention if silence is trimmed from the beginning and end of audio files." 
Just cite the words from https://github.com/NVIDIA/tacotron2/issues/111
Hope this help for you.
No. I am training on my own dataset.

**Comment by akshit-mittal-1** [comment]
I am training on my own data. After 70 iterations, it throws the error list index out of range.

Traceback (most recent call last):
  File "train.py", line 289, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 207, in train
    for i, batch in enumerate(train_loader):
  File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/tacotron2_prev/data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/home/ubuntu/tacotron2_prev/data_utils.py", line 32, in get_mel_text_pair
    audiopath, text = audiopath_and_text[0], audiopath_and_text[1]
IndexError: list index out of range

**Comment by WillQuCD** [comment]
> I am training on my own data. After 70 iterations, it throws the error list index out of range.
> 
> Traceback (most recent call last):
> File "train.py", line 289, in
> args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
> File "train.py", line 207, in train
> for i, batch in enumerate(train_loader):
> File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in **next**
> return self._process_next_batch(batch)
> File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> IndexError: Traceback (most recent call last):
> File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/ubuntu/tacotron2_prev/data_utils.py", line 61, in **getitem**
> return self.get_mel_text_pair(self.audiopaths_and_text[index])
> File "/home/ubuntu/tacotron2_prev/data_utils.py", line 32, in get_mel_text_pair
> audiopath, text = audiopath_and_text[0], audiopath_and_text[1]
> IndexError: list index out of range

check the sample rate of your audio. probably with a different sr.

**Comment by akshit-mittal-1** [comment]
> > I am training on my own data. After 70 iterations, it throws the error list index out of range.
> > Traceback (most recent call last):
> > File "train.py", line 289, in
> > args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
> > File "train.py", line 207, in train
> > for i, batch in enumerate(train_loader):
> > File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in **next**
> > return self._process_next_batch(batch)
> > File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
> > raise batch.exc_type(batch.exc_msg)
> > IndexError: Traceback (most recent call last):
> > File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
> > samples = collate_fn([dataset[i] for i in batch_indices])
> > File "/home/ubuntu/anaconda3/envs/tts/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in
> > samples = collate_fn([dataset[i] for i in batch_indices])
> > File "/home/ubuntu/tacotron2_prev/data_utils.py", line 61, in **getitem**
> > return self.get_mel_text_pair(self.audiopaths_and_text[index])
> > File "/home/ubuntu/tacotron2_prev/data_utils.py", line 32, in get_mel_text_pair
> > audiopath, text = audiopath_and_text[0], audiopath_and_text[1]
> > IndexError: list index out of range
> 
> check the sample rate of your audio. probably with a different sr.

Yeah, I figured the error. The data which was going in 71st iteration had some errors. Now its working fine and it has trained for nearly 100 iterations. The results are of medium quality. There are noises in the result. Anything I could do to improve the result ?
