### ISSUE TITLE
masked problem

### ISSUE THREAD

**Issue by truemanlee** [NVIDIA/tacotron2#133]
in model.py line 524:
`

    def parse_output(self, outputs, output_lengths=None):
        if self.mask_padding and output_lengths is not None:
            mask = ~get_mask_from_lengths(output_lengths)
            mask = mask.expand(self.n_mel_channels, mask.size(0), mask.size(1))
            mask = mask.permute(1, 0, 2)

            outputs[0].data.masked_fill_(mask, 0.0)
            outputs[1].data.masked_fill_(mask, 0.0)
            outputs[2].data.masked_fill_(mask[:, 0, :], 1e3)  # gate energies

        outputs = fp16_to_fp32(outputs) if self.fp16_run else outputs
        return outputs

`
It seems that the code 'outputs[2].data.masked_fill_(mask[:, 0, :], 1e3)' is not right. When training, it actually tells the model to give the all zero gate outputs.

**Comment by paarthneekhara** [comment]
@truemanlee 
Did you try omitting that line? Does it help the model to correctly predict the end of speech?
