### ISSUE TITLE
KeyError: 'optimizer' when running training from checkpoint

### ISSUE THREAD

**Issue by wanshun123** [NVIDIA/tacotron2#139]
I've downloaded the tacotron 2 model from https://drive.google.com/file/d/1c5ZTuT7J08wLUoVZ2KkUs_VdZuJ86ZqA/view?usp=sharing to the project directory and am trying to resume training from it as follows:

`python train.py --output_directory=outdir --log_directory=logdir --checkpoint_path tacotron2_statedict.pt
`

This results in the following:

```
FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
Loading checkpoint 'tacotron2_statedict.pt'
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 195, in train
    checkpoint_path, model, optimizer)
  File "train.py", line 105, in load_checkpoint
    optimizer.load_state_dict(checkpoint_dict['optimizer'])
KeyError: 'optimizer'
```

How should this be done?

**Comment by rafaelvalle** [comment]
The shared model is not to be used for checkpointing.

**Comment by caopan16** [comment]
How did you solve the problem?

**Comment by Yeongtae** [comment]
> How did you solve the problem?

Maybe u can load the shared model using 'Warm start'

**Comment by caopan16** [comment]
Thanks，I have fixed it.



------------------ 原始邮件 ------------------
发件人: "Yeongtae"<notifications@github.com>; 
发送时间: 2019年7月29日(星期一) 下午3:40
收件人: "NVIDIA/tacotron2"<tacotron2@noreply.github.com>; 
抄送: "草小妹"<815602984@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [NVIDIA/tacotron2] KeyError: 'optimizer' when running trainingfrom checkpoint (#139)



 
How did you solve the problem?
  
Maybe u can load the shared model using 'Warm start'

**Comment by peterwilson3912** [comment]
May I ask how did you solve it? Would you please show me the code? Thanks a lot!

**Comment by CookiePPP** [comment]
https://github.com/NVIDIA/tacotron2#training-using-a-pre-trained-model

---

## Training using a pre-trained model
Training using a pre-trained model can lead to faster convergence  
By default, the dataset dependent text embedding layers are [ignored]

1. Download our published [Tacotron 2] model
2. `python train.py --output_directory=outdir --log_directory=logdir -c tacotron2_statedict.pt --warm_start`

---

Use `--warm_start` to not load the optimizer inside the checkpoint file

**Comment by izhimahu** [comment]
> Thanks，I have fixed it.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Yeongtae"<notifications@github.com>; 发送时间: 2019年7月29日(星期一) 下午3:40 收件人: "NVIDIA/tacotron2"<tacotron2@noreply.github.com>; 抄送: "草小妹"<815602984@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [NVIDIA/tacotron2] KeyError: 'optimizer' when running trainingfrom checkpoint (#139) How did you solve the problem? Maybe u can load the shared model using 'Warm start' — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

May I ask how did you solve it?

**Comment by izhimahu** [comment]
May I ask how did you solve it?
