### ISSUE TITLE
how to show alignment image or mel image 

### ISSUE THREAD

**Issue by tsungruihon** [NVIDIA/tacotron2#148]
i train a model on chinese corpus , then used `tensorboard --logdir=output/log_dir/`, but the `tensorboard` not shown `alignment image` or `mel image`

**Comment by delgerdalai** [comment]
At least after 1000 iters, you can see alignment image

https://github.com/NVIDIA/tacotron2/issues/135#issuecomment-466033341

**Comment by tsungruihon** [comment]
in my `directory`, it has these files `checkpoint_0`  `checkpoint_1000`  `checkpoint_2000`  `checkpoint_3000`  `log_dir`.
therefore it should show the alignment image in tensorboard ?

**Comment by delgerdalai** [comment]
Yep, 
![screen shot 2019-02-21 at 11 46 04 pm](https://user-images.githubusercontent.com/3131525/53181699-04024380-3633-11e9-82bc-b9fd648a93f6.png)

localhost -> must be your training machine ip.

**Comment by tsungruihon** [comment]
thanks. it work now.!!
