### ISSUE TITLE
How is teacher forcing being annealed?

### ISSUE THREAD

**Issue by shreyasnivas** [NVIDIA/tacotron2#15]
Hi guys,
Some really great work here!

I'm trying to understand how tf is being applied in this model as compared to the Tacotron2 paper by Google.

As I understand it, in the paper, tf = 1.0 is applied for 50k steps before it is annealed (I would image, it goes all the way to 0)

Whereas in the code here, we can see tf being applied all the time during training.

`decoder_input = decoder_inputs[len(mel_outputs) - 1]`

And from some of the discussions on this repo we see that the Tacotron2 model does seem to generate(?) good samples when trained with full teacher forcing.

Quite confused how this could work unless there is some form of tf annealing being used.

@rafaelvalle could you please confirm whether I'm missing something?

Thanks!

**Comment by rafaelvalle** [comment]
Closing assuming there are no more issues.
