### ISSUE TITLE
Why are outputs of bidirectional lstm layers not summed up?

### ISSUE THREAD

**Issue by aaronlex** [NVIDIA/tacotron2#152]
In the Encoder layer in model.py an LSTM layer is set to bidirectional.
[https://github.com/NVIDIA/tacotron2/blob/master/model.py#L170](url)

But in the forward method, why isn't the output of the lstm layer summed up by doing something like:
`outputs = outputs[:, :, :int(hparams.encoder_embedding_dim / 2)] + outputs[:, : ,int(hparams.encoder_embedding_dim / 2):]`? Shouldn't the outputs of a bi-directional lstm be  summed up at each timestep?

**Comment by rafaelvalle** [comment]
PyTorche's LSTM Layer does it automatically when bidirectional is set to True..
