### ISSUE TITLE
Audio files duration matter?

### ISSUE THREAD

**Issue by hadaev8** [NVIDIA/tacotron2#154]
LJSpeech coverage while M-AILABS not
So I'm thinking, maybe because wavs duration?

Duration distributions for datasets:
LJSpeech
![](http://puu.sh/CT69r/b549f24e2b.jpg)
M-AILABS
![](http://puu.sh/CT6dA/006f98ee86.jpg)

Can I bypass it? (i can drop too long data obviously, but may be where is other ways)

**Comment by rafaelvalle** [comment]
The largest audio files will have an impact on how big your batch size can be.

**Comment by hadaev8** [comment]
Not only, I also find, it coverage only then I dropped too long wavs.

**Comment by WillQuCD** [comment]
@hadaev8 
How long is the too long wavs in your case? Greater than 20s or 30s?

**Comment by hadaev8** [comment]
@WillQuCD as you can see on pic, less then 30.
My problems was about batch size.
