### ISSUE TITLE
Humming in synthesized audio file?

### ISSUE THREAD

**Issue by aaronlex** [NVIDIA/tacotron2#155]
I have trained Tacotron for 437k steps and Wavenet for 720k steps on about 14 hours of audio data. So far when I've been testing it, the audio files I synthesize have a humming/noise-like sound in them. I'm using a sigma value of 0.666, increasing sigma doesn't help but lowering sigma increases the humming sound.

Is this something that more wavenet training will solve?
For tacotron2 after about 300k steps I lowered the learning rate to 1e-5.
And in Wavenet I changed sampling rate to 16kHz (my data is in 16kHz), n_channels is 256 (to avoid out of memory issues), and everything else is the same. 

Both models were trained on a single GPU.

My audio file: https://soundcloud.com/user-733941924/sample2-720kvocoder-437ktaco

**Comment by rafaelvalle** [comment]
Is this waveglow or wavenet?

**Comment by aaronlex** [comment]
It is waveglow, my mistake.

**Comment by rafaelvalle** [comment]
Hard to say without looking at your training logs. Generally speaking, keep training until the validation loss stops decreasing.

For removing the "humming sound" try using WaveGlow's denoiser.
https://github.com/NVIDIA/waveglow/blob/master/inference.py#L57

**Comment by aaronlex** [comment]
Does the inference notebook in Tacotron2 repo not use Waveglow's denoiser?

**Comment by aaronlex** [comment]
Thanks, the denoiser worked perfectly with a strength value of 0.1
