### ISSUE TITLE
Check Tacotron output w/o trained vocoder

### ISSUE THREAD

**Issue by AratorField** [NVIDIA/tacotron2#158]
I am training a Tacotron model with a custom dataset. 
In inference.py script I can check how well the model is a the moment but I have to have WaveGlow model to create waveform. I do not have computation power to train two models in parallel (Tacotron & WaveGlow). So now I cannot check how well Tacotron is doing because I cannot create waveform. Is there any option to create waveform directly from Tacotron without WaveGlow?

**Comment by tugstugi** [comment]
You can use the pretrained LJSpeech waveglow for any language. It will even work for a male voice.

**Comment by tugstugi** [comment]
Here is a synthesized example for a Mongolian male voice using the LJSpeech trained waveglow:

[10k_mongolian_ljspeech_vocoder.zip](https://github.com/NVIDIA/tacotron2/files/2926855/10k_mongolian_ljspeech_vocoder.zip)

**Comment by AratorField** [comment]
Unfortunately I have female voice.

**Comment by tugstugi** [comment]
Then, it will even work better. LJSpeech is a female voice.

**Comment by AratorField** [comment]
It is not sounds well. I feed it with mel_spectrogram created directly from wav file by `get_mel` method in `TextMelLoader`. 
I use default hparams.

[pretrained_waveglow.wav.zip](https://github.com/NVIDIA/tacotron2/files/2927169/pretrained_waveglow.wav.zip)

**Comment by delgerdalai** [comment]
Your wav file is 32(float). You have to change normalization code.
<img width="792" alt="screen shot 2019-03-05 at 3 19 29 pm" src="https://user-images.githubusercontent.com/3131525/53787526-21e87600-3f5a-11e9-8d3f-9200ef7dd4b9.png">

[generated_pretrained_LJS.wav.zip](https://github.com/NVIDIA/tacotron2/files/2929676/generated_pretrained_LJS.wav.zip) is generated by pretrained LJS pretrained. It sounds pretty well.

**Comment by AratorField** [comment]
@delgerdalai Thanks! Sounds much better.
It won't be a problem that each audio file will be normalized using different value? Or I should put there some constant value which will fit the whole dataset?

**Comment by delgerdalai** [comment]
I think goal is convert audio file to [-1, 1] range. 

I don't know about wav 32bit float file format. Maybe you can find maximum value of whole dataset and then you can use it by constant.

Or just **audio_norm = audio / audio.max()** might be better. 

for 16bit int wav file:

**audio_norm = audio / 16bit integer maximum value.**
_LJS dataset wav is 16bit integer. Therefore hparams.max_wav_value is 32767._

**Comment by AratorField** [comment]
Thank you. It looks like files are already normalized and values are in the range <-1,1>. 
No need to do normalization in my case :)
