### ISSUE TITLE
RuntimeError: torch/csrc/autograd/variable.cpp:138: get_grad_fn: Assertion `output_nr_ == 0` failed.

### ISSUE THREAD

**Issue by abuvaneswari** [NVIDIA/tacotron2#16]
Hello,

Centos 7
Python 3.6
CUDA 9

Used conda for installing pytorch for this configuration. 

Had to remove the version specification for numpy and torch in your requirements.txt as I got the error message logged in issue #5 

Now,
numpy = 1.14.3
torch = 0.4.0
tensorflow = 1.6.0

After the requirements installation, when I run train.py, I get the following error. 

Please help:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
python train.py --output_directory=./outdir --log_directory=./logdir
/home/tacotron2/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
FP16 Run: False
Dynamic Loss Scaling True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
/home/tacotron2/tacotron2/layers.py:35: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  self.conv.weight, gain=torch.nn.init.calculate_gain(w_init_gain))
/home/tacotron2/tacotron2/layers.py:15: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  gain=torch.nn.init.calculate_gain(w_init_gain))
Epoch: 0
Traceback (most recent call last):
  File "train.py", line 285, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 210, in train
    y_pred = model(x)
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tacotron2/tacotron2/model.py", line 506, in forward
    encoder_outputs = self.encoder(embedded_inputs, input_lengths)
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tacotron2/tacotron2/model.py", line 188, in forward
    outputs, _ = self.lstm(x)
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 192, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 323, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/tacotron2/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 287, in forward
    dropout_ts)
RuntimeError: torch/csrc/autograd/variable.cpp:115: get_grad_fn: Assertion `output_nr == 0` failed.

**Comment by rafaelvalle** [comment]
@abuvaneswari what is your pytorch version?

**Comment by rafaelvalle** [comment]
@raulpuric any thoughts on this?

**Comment by abuvaneswari** [comment]
Hello,

thanks for looking into this. I used the following command to install pytorch.
conda install pytorch torchvision cuda90 -c pytorch

torch version is 0.4.0
Please let me know the command to find pytorch version

thanks,
Buvana

**Comment by rafaelvalle** [comment]
For sanity check: are you running on multiple gpus, single gpu, cpu?

**Comment by abuvaneswari** [comment]
Multiple GPUs. Volta.

**Comment by rafaelvalle** [comment]
Please run with DistributedDataParallel instead of DataParallel and let us know.
`python -m multiproc train.py --output_directory=./outdir --log_directory=./logdir --hparams=distributed_run=True`

**Comment by raulpuric** [comment]
So by default the code detects if you have multiple gpus available, and if you do it will automatically wrap the model in dataparallel unless you force it to use Distributed data parallel via the `python -m multiproc train.py`. For some reason ever since upgrading to 0.4 DataParallel hasn't been working properly for us.

If you don't want to use some form of data parallelism in your training I would recommend throwing a `CUDA_VISIBLE_DEVICES=0 python train.py <...>` in your command line.

**Comment by abuvaneswari** [comment]
Hello,

Thanks a lot for your suggestion. 

export CUDA_VISIBLE_DEVICES="0" and then executing the train.py is successful! But the step time is reported as 4 sec on a Pascal. Is that expected? How many steps I need to execute before a decent model can be arrived at?

export CUDA_VISIBLE_DEVICES="0,1,2,3" and then executing the following command results in an initial error message, but I think the thread or another process that it spawns continues to run, but I do not see any more output (been staring for 10 minutes) after the 'initializing distributed' line.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
['train.py', '--output_directory=./outdir_mgpu', '--log_directory=./logdir_mgpu', '--hparams=distributed_run=True', '--n_gpus=4', '--group_name=group_2018_05_11-223841', '--rank=0']
Traceback (most recent call last):
  File "/home/tacotron2/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tacotron2/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tacotron2/tacotron2/multiproc.py", line 16, in <module>
    "w")
FileNotFoundError: [Errno 2] No such file or directory: 'logs/2018_05_11-223841_GPU_1.log'
[tacotron2@blipp77 tacotron2]$ /home/tacotron2/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
FP16 Run: False
Dynamic Loss Scaling True
Distributed Run: True
cuDNN Enabled: True
cuDNN Benchmark: False
Initializing distributed

**Comment by rafaelvalle** [comment]
`export CUDA_VISIBLE_DEVICES="0" and then executing the train.py is successful! But the step time is reported as 4 sec on a Pascal.` 
Is this with DataParallel or Distributed? Distributed is considerably faster than DataParallel. 

Number of iterations to reach decent model is data, pre-processing and GPU dependent.
The model is decent once it has learned attention.

**Comment by abuvaneswari** [comment]
@rafaelvalle , thanks. I set CUDA_VISIBLE_DEVICES to one of the GPUs. I do not know if by default it is DataParallel or Distributed.

I asked the question about the num steps needed for a decent model because I see in some tacotron TTS repos (such as from keithito, mozilla/tts, kyubyong), the authors sharing the checkpoint and generated samples at a certain step # where the alignment is good and the resulting sample sounds decent. 

To be specific, I was wondering if you can share your experience with the LJ dataset.

I would appreciate if you can respond on the error message that I see when I run Distributed DataParallel. Please scroll up and check my past posting.

**Comment by rafaelvalle** [comment]
@abuvaneswari sorry for the slow response. You have a `FileNotFoundError`. 
Please try creating a `logs/` folder in your tacotron2 and let us know if the problem persists.

**Comment by IwraStudios** [comment]
@rafaelvalle `mkdir logs` fixes the error, but it keeps waiting on the other process (last line in multiproc.py) without actually training

**Comment by rafaelvalle** [comment]
@IwraStudios can you please make sure there's not a distributed.dpt file in the folder from which you're running the model? If the file is there, try erasing it and running it again. 
Let us know if it still doesn't work.

**Comment by IwraStudios** [comment]
@rafaelvalle It fixes the problem but now a different problem has arisen: #32

**Comment by rafaelvalle** [comment]
Closing. Please re-open if there's still an issue.
