### ISSUE TITLE
How to reduce hissyness/robotic sound in result?

### ISSUE THREAD

**Issue by wanshun123** [NVIDIA/tacotron2#161]
I am training Tacotron 2 from scratch on my own dataset of about 5.5 hours of audio (across nearly 15,000 audio files, formatted the same as LJ Speech) and have intelligible results, but there remains a robotic noise in the background:

[results.zip](https://github.com/NVIDIA/tacotron2/files/2935333/results.zip)

When training the loss gets to a minimum of around 0.84 then starts to go back up again, here is my training log:

[train.log](https://github.com/NVIDIA/tacotron2/files/2935335/train.log)

Here is also my training log from training on LJSpeech - the avg_loss gets down to a minimum of around 0.86 then creeps back up again. Would like to hear from anyone who has achieved better results.

[LJSpeech-train.log](https://github.com/NVIDIA/tacotron2/files/2935342/LJSpeech-train.log)
[LJSpeech-results (1).zip](https://github.com/NVIDIA/tacotron2/files/2935343/LJSpeech-results.1.zip)

Should these results be able to be improved?

**Comment by rafaelvalle** [comment]
https://github.com/NVIDIA/tacotron2/issues/162#issuecomment-473481824
