### ISSUE TITLE
SyntaxError: invalid syntax (jupyter, anaconda, windows10)

### ISSUE THREAD

**Issue by tiazgriff** [NVIDIA/tacotron2#165]
`import matplotlib
matplotlib.use("Agg")
import matplotlib.pylab as plt
%matplotlib inline
import IPython.display as ipd

import sys
sys.path.append('waveglow/')
import numpy as np
import torch

from hparams import create_hparams
from model import Tacotron2
from layers import TacotronSTFT, STFT
from audio_processing import griffin_lim
from train import load_model
from text import text_to_sequence
from denoiser import Denoiser`
`Traceback (most recent call last):

  File "G:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-c399d9d7afcf>", line 13, in <module>
    from model import Tacotron2

  File "G:\waveglow\tacotron2\model.py", line 6, in <module>
    from utils import to_gpu, get_mask_from_lengths

  File "G:\waveglow\tacotron2\utils.py", line 31
    x = x.contiguous().cuda(async=True)
                                ^
SyntaxError: invalid syntax`

**Comment by rafaelvalle** [comment]
Pull from master: utils.py in tacotron 2 has only 29 lines and your error is on line 31.
