### ISSUE TITLE
It's working now---using Chinese corpus

### ISSUE THREAD

**Issue by maozhiqiang** [NVIDIA/tacotron2#17]
the plot like 
![screenshot from 2018-05-14 15-26-33](https://user-images.githubusercontent.com/23501322/39983782-7a2c9ac4-578b-11e8-9ae2-9b3d9f0a668e.png)
the train is very slowing

**Comment by rafaelvalle** [comment]
That is great to know, @maozhiqiang!
What exactly is slow? the training iteration or the time it takes to learn attention?
What is your setup?

**Comment by rafaelvalle** [comment]
@begeekmyfriend please move this comment and discussion here: https://github.com/NVIDIA/tacotron2/issues/12

**Comment by maozhiqiang** [comment]
@rafaelvalle I training useing one GPU ,so the training is so slowing !and the attention is not until the twenty thousand step begins to align！

**Comment by rafaelvalle** [comment]
Training time is probably dominated by computing mel-spectrograms on the CPU and can be amortized by pre-processing the mel-spectrograms and loading them from disk.

We're looking into speeding up the model such that the attention is learned faster.

**Comment by rafaelvalle** [comment]
@maozhiqiang What is your iterations per second time on average?

**Comment by rafaelvalle** [comment]
FYI: We've added the option to load mels from disk.

**Comment by maozhiqiang** [comment]
@rafaelvalle thanks! The following is training log 
[train_log.log](https://github.com/NVIDIA/tacotron2/files/2007095/train_log.log)

**Comment by rafaelvalle** [comment]
@maozhiqiang What GPU do you have?

**Comment by maozhiqiang** [comment]
P5000

**Comment by rafaelvalle** [comment]
To me, the iterations per second seem comparable to what I've seen with Taco 2 implementations.
It should be less of a hassle once we improve model to learn attention faster.

**Comment by maozhiqiang** [comment]
@rafaelvalle thanks!

**Comment by rafaelvalle** [comment]
@maozhiqiang please re-run your experiments on the branch below and and let us know what your convergence time is. In this branch, the model attends to the full mel-spectrogram instead of the prenet drop out mel: this should increase convergence time considerably.
https://github.com/NVIDIA/tacotron2/tree/attention_full_mel

**Comment by maozhiqiang** [comment]
@rafaelvalle thanks , I will try this

**Comment by rafaelvalle** [comment]
@maozhiqiang great. We'll soon add dropout as well.

**Comment by root20** [comment]
@maozhiqiang Could you share what Chinese corpus you have used?

**Comment by maozhiqiang** [comment]
sorroy ! The data is not open!

**Comment by rafaelvalle** [comment]
Closing. Please re-open if the issues haven't been solved.

**Comment by begeekmyfriend** [comment]
@maozhiqiang Would you please open your modification on this project for Chinese mandarin on your repo?

**Comment by maozhiqiang** [comment]
@begeekmyfriend  yes! i uploaded ! please go to https://github.com/maozhiqiang/tacotron2_pytorch.git

**Comment by NewEricWang** [comment]
Hi, @maozhiqiang , could you share some synthesized speech samples in Chinese tacotron2 project?  What is the unit you used? How do you control the tone of the synthesized speech?

**Comment by jinfagang** [comment]
@maozhiqiang The link is missing

**Comment by tsungruihon** [comment]
@maozhiqiang the link is missing too.

**Comment by tsungruihon** [comment]
@maozhiqiang  could you share you `hparams.py` detail ?
