### ISSUE TITLE
Increasing duration of pause between sentences?

### ISSUE THREAD

**Issue by Cacozelia** [NVIDIA/tacotron2#173]
Hi

I was wondering whether there is a way of increasing the length of the pause generated by the pre-trained model between sentences. Obviously this could be done in post-production, but is there a means of extending this pause when generating the audio?

**Comment by rafaelvalle** [comment]
Not trivial without training a new model. Did you try increasing the number of spaces between words?

**Comment by Cacozelia** [comment]
Hi @rafaelvalle yes, I tried this but it didn't work. Spacing doesn't seem to make any difference. 

However, adding an ellipsis increases the length of the pause between sentences from 200ms to 420ms, e.g 'The cat sat on the mat. And then got up'/'The cat sat on the mat...and then got up'

**Comment by rafaelvalle** [comment]
Yes, ellipsis could also work!
