### ISSUE TITLE
unstable tacotron output

### ISSUE THREAD

**Issue by hadaev8** [NVIDIA/tacotron2#180]
So, I fine-tuned published model to 0.25 loss.
Seems it will not become better
![](http://puu.sh/Db2ft/75a18f643a.png)

But every interference run is very different.
Outputs for same text:

![](http://puu.sh/Db2lb/8a5049b0c1.jpg)

![](http://puu.sh/Db2lU/d6ddc1af60.jpg)

![](http://puu.sh/Db2mA/3f486adccb.jpg)

**Comment by rafaelvalle** [comment]
Yes! Like human speech, the model has variety over the same sentence.
https://github.com/NVIDIA/tacotron2/blob/master/model.py#L99

**Comment by hadaev8** [comment]
The problem is: It jump from more or less good to eat some words.
While published model have around same output and never lost words, what did i wrong?
