### ISSUE TITLE
RuntimeError: Address already in use

### ISSUE THREAD

**Issue by lsuperman** [NVIDIA/tacotron2#181]

**Comment by lsuperman** [comment]
hello, everyone, I am trying to run the tacotron2 with 2 gpu, my command is
CUDA_VISIBLE_DEVICES=0,1 nohup /opt/anaconda3-5.1.0/bin/python3.6 -m multiproc train.py --output_directory=outdir --log_directory=logdir -c outdir/checkpoint_13000 --warm_start >> output.out &
but,the output as following:

FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: True
cuDNN Enabled: True
cuDNN Benchmark: False
Initializing Distributed
Traceback (most recent call last):
  File "train.py", line 303, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 179, in train
    init_distributed(hparams, n_gpus, rank, group_name)
  File "train.py", line 49, in init_distributed
    world_size=n_gpus, rank=rank, group_name=group_name)
  File "/opt/anaconda3-5.1.0/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 354, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/opt/anaconda3-5.1.0/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 95, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, start_daemon)
RuntimeError: Address already in use
/opt/anaconda3-5.1.0/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:86: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'outdir/checkpoint_13000', '--warm_start', '--n_gpus=2', '--group_name=group_2019_04_10-105411', '--rank=0']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'outdir/checkpoint_13000', '--warm_start', '--n_gpus=2', '--group_name=group_2019_04_10-105411', '--rank=1']
~

**Comment by lsuperman** [comment]
Any ideas would be greatly appreciated

**Comment by delgerdalai** [comment]
Your previous execution not completely terminated. 
`netstat -nltp` this command will show process lists which are listen ports. Now, you have to kill process which is listen 54321 port. `kill -9 PID.` in this case. `kill -9 1594`. Then try to start training. 

![Screen Shot 2019-04-10 at 5 02 30 PM](https://user-images.githubusercontent.com/3131525/55866209-72cf3800-5bb2-11e9-9177-c5910b1c4924.jpg)

**Comment by lsuperman** [comment]
@delgerdalai  thanks
