### ISSUE TITLE
Saying uncommon abbreviations

### ISSUE THREAD

**Issue by aaronlex** [NVIDIA/tacotron2#185]
If I want to my model to be able to say some abbreviations (CEO, VP, etc. letter by letter ex: CEO is see e oh) would it be better to add the arpabet equivalent to `_abbreviations` in cleaners.py **before** training or make these changes after training? I don't have too many of these instances in my training dataset but I want my model to be able to handle these abbreviations during inference.

**Comment by rafaelvalle** [comment]
You can certainly look for abbreviations and their respective ARPAbets. A more general solution is to finds acronyms and convert them to arpabet by pronouncing each letter independently? CEO : {S IY}  {IY} {OW} instead of {S IY IY OW}.
