### ISSUE TITLE
waveglow tacotron2 circular dependency

### ISSUE THREAD

**Issue by loretoparisi** [NVIDIA/tacotron2#189]
The submodule `tacotron2` has as submodule the `tacotron2` module that is the root module itself (in a different branch than the master branch). Is that necessary or a circular dependency error?

```
tacotron2 (@c76ac3b)
| - waveglow  (@ 4b1001f)
   |-tacotron2 (@ fc0cf6a)
```

**Comment by rafaelvalle** [comment]
Whereas Tacotron2 uses/depends on waveglow's repo for synthesis, waveglow uses/depends on tacotron2's repo for mel-spectrogram processing, hence the "circular dependency". 
This should bring any issues to either repos.

**Comment by loretoparisi** [comment]
@rafaelvalle okay, so basically when cloned, to avoid duplicating the code, the path can be adjusted so that `tacotron2` will be there once while keeping the references, right?

**Comment by rafaelvalle** [comment]
Yes
