### ISSUE TITLE
ImportError: cannot import name 'apply_gradient_allreduce'

### ISSUE THREAD

**Issue by angeloh** [NVIDIA/tacotron2#207]
Hello,

I'm trying to run `inference.ipynb` on Google Colab but I faced this issue during the import. I can see the method `apply_gradient_allreduce` in train.py.

```
ImportError                               Traceback (most recent call last)
<ipython-input-70-fd81229d5640> in <module>()
     12 from layers import TacotronSTFT, STFT
     13 from audio_processing import griffin_lim
---> 14 from train import load_model
     15 from text import text_to_sequence
     16 from waveglow.denoiser import Denoiser

/content/drive/My Drive/Workspaces/tacotron2/train.py in <module>()
      6 
      7 import torch
----> 8 from distributed import apply_gradient_allreduce
      9 import torch.distributed as dist
     10 from torch.utils.data.distributed import DistributedSampler

ImportError: cannot import name 'apply_gradient_allreduce'
```

**Comment by rafaelvalle** [comment]
I'm surprised Google Colab can't import apply_gradient_allreduce from distributed.py.
A quick *hack* is to copy/paste the code from load_model to inference.py and remove the import.

**Comment by kunaia** [comment]
`!pip uninstall --yes protobuf`
`!pip install --no-binary=protobuf protobuf`

try this, restart kernel and run cells again.
that worked for me ;)
