### ISSUE TITLE
image of alignment is a horizontal line

### ISSUE THREAD

**Issue by heshulin** [NVIDIA/tacotron2#209]
encoder and decoder Cannot align，the image of alignment is a horizontal line

**Comment by rafaelvalle** [comment]
Provide more information about your dataset and setup.

**Comment by heshulin** [comment]
> 提供有关数据集和设置的更多信息。

dataset https://www.data-baker.com
Chinese use jieba library to   pinyin
Maybe I need to add tone information?

**Comment by rafaelvalle** [comment]
Tone information should not be necessary.
Make sure you have proper [cleaners](https://github.com/NVIDIA/tacotron2/blob/master/text/cleaners.py) and [symbols](https://github.com/NVIDIA/tacotron2/blob/master/text/symbols.py).

**Comment by heshulin** [comment]
@rafaelvalle  text_cleaners=['transliteration_cleaners']  symbols no modification

**Comment by rafaelvalle** [comment]
Check that the data is correct and that you have no silence at the beginning and end of audio files.

**Comment by heshulin** [comment]
@rafaelvalle ok,vad is necessary ，thank you very much

**Comment by rafaelvalle** [comment]
Glad to hear that using voice activity detection solves your problem!

**Comment by Approximetal** [comment]
@rafaelvalle [Here](https://github.com/NVIDIA/tacotron2/issues/269#issuecomment-536369814) said it would performed better to learn alignment if add 5*hop_size at the end of the the audio. But this answer said we should remove the slience. Therefore I was cofused whether the silence at the end of audio file should be added or removed? BTW, the alignment in my model is always a horizontal line, is there any suggest I can get?

**Comment by rafaelvalle** [comment]
First check that there's no mismatch between the audio and the transcription.
Remove silence from the beginning and end of your audio file and start from the pre-trained model.
This should work.
