### ISSUE TITLE
Sampling Rate differences

### ISSUE THREAD

**Issue by akshitmittal1** [NVIDIA/tacotron2#210]
I am training on the pre-trained model with my own dataset which is about 7 hours of audio with sampling rate = 16000 with a batch size of 32. Will model give some good results if I train on sampling rate = 16000 or do I need to resample my data at 22050 for getting good results?

**Comment by akshit-mittal-1** [comment]
After training for nearly 100 iterations, the results are noises only. Do I need to change anything in Inference notebook other than sampling rate =16000?

**Comment by pravn** [comment]
I think if you are using a pretrained model (ljspeech?) you should resample
to 22050. I have also had similar issues with Arctic which is at 16 khz.

pravn.wordpress.com

**Comment by akshit-mittal-1** [comment]
Hi, I first trained my model with 16khz with my data. After nearly 100 epochs, results were very good, I could hear the text which I was giving as input but the problem coming was that output audio was very fast, I mean words were spoken very fast.
