### ISSUE TITLE
Can't load pretrained models in inference.ipynb

### ISSUE THREAD

**Issue by 41WhiteElephants** [NVIDIA/tacotron2#216]
I'm just trying to use the published pre-trained models with the default ipynb file and receiving the following errors: 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-7bcdd64c5965> in <module>
      1 checkpoint_path = "tacotron2_statedict.pt"
      2 model = load_model(hparams)
----> 3 model.load_state_dict(torch.load(checkpoint_path)['state_dict'])
      4 _ = model.cuda().eval().half()

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    719         if len(error_msgs) > 0:
    720             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 721                                self.__class__.__name__, "\n\t".join(error_msgs)))
    722 
    723     def parameters(self):

RuntimeError: Error(s) in loading state_dict for Tacotron2:
	Unexpected key(s) in state_dict: "encoder.convolutions.0.1.num_batches_tracked", "encoder.convolutions.1.1.num_batches_tracked", "encoder.convolutions.2.1.num_batches_tracked", "postnet.convolutions.0.1.num_batches_tracked", "postnet.convolutions.1.1.num_batches_tracked", "postnet.convolutions.2.1.num_batches_tracked", "postnet.convolutions.3.1.num_batches_tracked", "postnet.convolutions.4.1.num_batches_tracked". 

And further when I'm trying to load yours waveglow model:

---------------------------------------------------------------------------
NotSupportedError                         Traceback (most recent call last)
<ipython-input-15-2da93720e586> in <module>
      1 waveglow_path = 'waveglow/waveglow_256channels.pt'
----> 2 waveglow = torch.load(waveglow_path)['model']
      3 

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/serialization.py in load(f, map_location, pickle_module)
    301         f = open(f, 'rb')
    302     try:
--> 303         return _load(f, map_location, pickle_module)
    304     finally:
    305         if new_fd:

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/serialization.py in _load(f, map_location, pickle_module)
    467     unpickler = pickle_module.Unpickler(f)
    468     unpickler.persistent_load = persistent_load
--> 469     result = unpickler.load()
    470 
    471     deserialized_storage_keys = pickle_module.load(f)

~/tacotron2/waveglow/glow.py in <module>
     31 
     32 
---> 33 @torch.jit.script
     34 def fused_add_tanh_sigmoid_multiply(input_a, input_b, n_channels):
     35     n_channels_int = n_channels[0]

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/__init__.py in script(fn)
    535 
    536 def script(fn):
--> 537     graph = _script_graph(fn, frame_id=3)
    538     return torch._C.GraphExecutor(graph, True)
    539 

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/__init__.py in _script_graph(fn, frame_id)
    530 def _script_graph(fn, frame_id=2):
    531     rcb = createResolutionCallback(frame_id)
--> 532     ast = get_jit_ast(fn)
    533     return _jit_script_compile(ast, rcb)
    534 

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in get_jit_ast(fn)
    125     if len(py_ast.body) != 1 or not isinstance(py_ast.body[0], ast.FunctionDef):
    126         raise RuntimeError("expected a single top-level function")
--> 127     return build_def(SourceRangeFactory(source), py_ast.body[0])
    128 
    129 

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in build_def(ctx, py_def)
    144     return Def(Ident(r, py_def.name),
    145                build_param_list(ctx, py_def.args),
--> 146                [build_stmt(ctx, stmt) for stmt in body])
    147 
    148 

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in <listcomp>(.0)
    144     return Def(Ident(r, py_def.name),
    145                build_param_list(ctx, py_def.args),
--> 146                [build_stmt(ctx, stmt) for stmt in body])
    147 
    148 

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in __call__(self, ctx, node)
    133         if method is None:
    134             raise UnsupportedNodeError(ctx, node)
--> 135         return method(ctx, node)
    136 
    137 

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in build_Assign(ctx, stmt)
    192     @staticmethod
    193     def build_Assign(ctx, stmt):
--> 194         rhs = build_expr(ctx, stmt.value)
    195         if len(stmt.targets) > 1:
    196             start_point = ctx.make_range(stmt.lineno, stmt.col_offset, stmt.col_offset + 1)

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in __call__(self, ctx, node)
    133         if method is None:
    134             raise UnsupportedNodeError(ctx, node)
--> 135         return method(ctx, node)
    136 
    137 

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in build_Call(ctx, expr)
    297     def build_Call(ctx, expr):
    298         func = build_expr(ctx, expr.func)
--> 299         args = [build_expr(ctx, py_arg) for py_arg in expr.args]
    300         if hasattr(expr, 'starargs') and expr.starargs:
    301             stararg_expr = build_expr(ctx, expr.starargs)

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in <listcomp>(.0)
    297     def build_Call(ctx, expr):
    298         func = build_expr(ctx, expr.func)
--> 299         args = [build_expr(ctx, py_arg) for py_arg in expr.args]
    300         if hasattr(expr, 'starargs') and expr.starargs:
    301             stararg_expr = build_expr(ctx, expr.starargs)

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in __call__(self, ctx, node)
    133         if method is None:
    134             raise UnsupportedNodeError(ctx, node)
--> 135         return method(ctx, node)
    136 
    137 

~/anaconda2/envs/myenv/lib/python3.6/site-packages/torch/jit/frontend.py in build_Subscript(ctx, expr)
    404             return Slice(base, lower, upper)
    405         elif sub_type is ast.ExtSlice:
--> 406             raise NotSupportedError(base.range(), "slicing multiple dimensions at the same time isn't supported yet")
    407         else:  # Ellipsis (can only happen in Python 2)
    408             raise NotSupportedError(base.range(), "ellipsis is not supported")

NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
@torch.jit.script
def fused_add_tanh_sigmoid_multiply(input_a, input_b, n_channels):
    n_channels_int = n_channels[0]
    in_act = input_a+input_b
    t_act = torch.tanh(in_act[:, :n_channels_int, :])
                       ~~~~~~ <--- HERE
    s_act = torch.sigmoid(in_act[:, n_channels_int:, :])
    acts = t_act * s_act
    return acts


My system is OpenSuse 43.2 and I'm using Python 3.6 on anaconda.

**Comment by rafaelvalle** [comment]
Looks like you have a pytorch version mismatch.

**Comment by 41WhiteElephants** [comment]
What do you mean by that? My version is torch==1.0.1.post2 with
torchvision==0.2.2. So it's version you said to install in setup instruction.
