### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by jferrer21** [NVIDIA/tacotron2#226]
I trained the tacotron2 with my own data.  When performing the inference with the Jupyter Notebook, on the section "Load model from checkpoint", there is a "tacotron2_statedict.pt" file.  How do I create my own "*.pt" file from the "checkpoint" files?  Can someone point me in the right direction?

Thank you so much!!
@rafaelvalle

**Comment by akshitmittal1** [comment]
while training your model, you must have given a name for outdirectory, check for a folder named outdir in the tacotron2 folder...you will find checkpoints there, enter those checkpoints while inferencing

**Comment by jferrer21** [comment]
Thank you for your response.  The question is how do I give those checkpoints while inferencing.  Do I give the last checkpoint or do I place all of them on an array?  Do I need to convert the checkpoint file to an *.pt file?

**Comment by akshitmittal1** [comment]
Just give the path of a checkpoint in the checkpoint_path, there is no need to place anything in an array or to convert anything in a .pt file

**Comment by jferrer21** [comment]
Perfect.  Thank you.

@akshitmittal1

**Comment by jferrer21** [comment]
On the inference step, and when running the following code, there is an error.

I added the "waveglow_280000" file to the current directory, and it has the right permissions. 

I'm using Pytorch 1.1 and Cuda 10.  I also ran the following commands on the current directory: git submodule init; git submodule update.

> Load WaveGlow for mel2audio synthesis and denoiser

```
waveglow_path = "waveglow_280000"
waveglow = torch.load(waveglow_path)['model']
waveglow.cuda().eval().half()
for k in waveglow.convinv:
    k.float()
denoiser = Denoiser(waveglow)

```
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-26-5c3a046c36ea> in <module>
      1 waveglow_path = "waveglow_280000"
----> 2 waveglow = torch.load(waveglow_path)['model']
      3 waveglow.cuda().eval().half()
      4 for k in waveglow.convinv:
      5     k.float()

~/anaconda3/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    385         f = f.open('rb')
    386     try:
--> 387         return _load(f, map_location, pickle_module, **pickle_load_args)
    388     finally:
    389         if new_fd:

~/anaconda3/lib/python3.7/site-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    572     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    573     unpickler.persistent_load = persistent_load
--> 574     result = unpickler.load()
    575 
    576     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

ModuleNotFoundError: No module named 'glow'
```

@akshitmittal1

**Comment by jferrer21** [comment]
I rebooted the computer and it seems to be working now.  However, I'm getting a warning:

/```
~/anaconda3/lib/python3.7/site-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'glow.Invertible1x1Conv' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
waveglow/glow.py:162: RuntimeWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  torch.IntTensor([self.n_channels]))
waveglow/glow.py:162: RuntimeWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  torch.IntTensor([self.n_channels]))
```
 


@akshitmittal1

**Comment by rafaelvalle** [comment]
You can ignore those warnings.

**Comment by EuphoriaCelestial** [comment]
I am running inference in nvidia-docker image and got the same error

Traceback (most recent call last):
  File "inference.py", line 253, in <module>
    main()
  File "inference.py", line 199, in main
    args.amp_run, forward_is_infer=True)
  File "inference.py", line 113, in load_and_setup_model
    state_dict = torch.load(checkpoint)['state_dict']
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 482, in load
    return _load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 683, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'glow'

I tried reload daemon, restart docker, but it not working.
My inference command:
`python inference.py --tacotron2 checkpoints/vietnamese/checkpoint_344000 --waveglow checkpoints/vietnamese/waveglow_256channels_ljs_v2_new.pt -o output/ --include-warmup -i phrases/phrase_1_64.txt --amp-run --log-file=nvlog_fp16.json`

**Comment by rafaelvalle** [comment]
Make sure you run 
```
git submodule init
git submodule update
```

**Comment by EuphoriaCelestial** [comment]
@rafaelvalle I solved it by download glow.py file from git and put it into project folder. Now it come to this error:

Traceback (most recent call last):
  File "test_infer.py", line 226, in <module>
    main()
  File "test_infer.py", line 172, in main
    waveglow = load_and_setup_model('WaveGlow', parser, args.waveglow, args.amp_run)
  File "test_infer.py", line 82, in load_and_setup_model
    state_dict = torch.load(checkpoint)['state_dict']
KeyError: 'state_dict'

**Comment by evelynyhc** [comment]
> Just give the path of a checkpoint in the checkpoint_path, there is no need to place anything in an array or to convert anything in a .pt file

hello, i have the same problem as you, when i want to use my own checkpoint, i try this code:

checkpoint_path = './outdir/checkpoint_29000'
model.load_state_dict(torch.load(checkpoint_path)['state_dict'])

but there are some errors, like  [Errno 21] Is a directory: './outdir/checkpoint_29000'
please help me about it, thanks!

**Comment by evelynyhc** [comment]
> I trained the tacotron2 with my own data. When performing the inference with the Jupyter Notebook, on the section "Load model from checkpoint", there is a "tacotron2_statedict.pt" file. How do I create my own "*.pt" file from the "checkpoint" files? Can someone point me in the right direction?
> 
> Thank you so much!!
> @rafaelvalle

I trained the tacotron2 with my own data. When performing the inference with the Jupyter Notebook, on the section "Load model from checkpoint", there is a "tacotron2_statedict.pt" file. How do I create my own "*.pt" file from the "checkpoint" files? Can someone point me in the right direction?

Thank you so much!!
@rafaelvalle

**Comment by CookiePPP** [comment]
@evelynyhc 
You can use any `checkpoint_XXXXX` file. It does not have to have `.pt` on the end.

**Comment by evelynyhc** [comment]
> @evelynyhc
> You can use any `checkpoint_XXXXX` file. It does not have to have `.pt` on the end.
but if i use checkpoint_xxx, it also have some problem :

IsADirectoryError: [Errno 21] Is a directory: './outdir/checkpoint_29000'

how to solve it, thanks!

**Comment by CookiePPP** [comment]
> IsADirectoryError: [Errno 21] Is a directory: './outdir/checkpoint_29000'

Well, that error means that `'./outdir/checkpoint_29000'` is apparently a folder. I'm not sure how this was able to happen.

Upload a screenshot of the `outdir` folder if you can't figure it out. I'm guessing you accidently created a folder with the same name as a file or are using the wrong name.

**Comment by evelynyhc** [comment]
> > IsADirectoryError: [Errno 21] Is a directory: './outdir/checkpoint_29000'
> 
> Well, that error means that `'./outdir/checkpoint_29000'` is apparently a folder. I'm not sure how this was able to happen.
> 
> Upload a screenshot of the `outdir` folder if you can't figure it out. I'm guessing you accidently created a folder with the same name as a file or are using the wrong name.

ok, i have solved it . I trained the model on the server, then downloaded the file locally, and uncompressed the file easily, which caused this problem, which is really embarrassing.
appreciate  for your answer and help!
