### ISSUE TITLE
where is the denoiser? 

### ISSUE THREAD

**Issue by NileZhou** [NVIDIA/tacotron2#227]
in file inference.ipynb, 
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-1e40ea2a3544> in <module>()
     16 from train import load_model
     17 from text import text_to_sequence
---> 18 from denoiser import Denoiser

ModuleNotFoundError: No module named 'denoiser'`

if the denoiser is in apex or other python models?

**Comment by akshitmittal1** [comment]
denoiser is a .py file in the repository itself.

**Comment by NileZhou** [comment]
> denoiser is a .py file in the repository itself.
thanks. but I still don't understand, i can't find the file in tacotron2

**Comment by NileZhou** [comment]
> denoiser is a .py file in the repository itself.

thanks. but I still don't understand, i can't find the file in tacotron2

**Comment by akshitmittal1** [comment]
okay, I don't know why is that happening but you can just copy its code and make a .py file denoiser itself to make it work

**Comment by vikrantsharma7** [comment]
It's in the waveglow repo.
`sys.path.append('waveglow/')`

**Comment by NileZhou** [comment]
> It's in the waveglow repo.
> `sys.path.append('waveglow/')`
> 
> If still not found
> 
> ```
> cd waveglow/
> git pull origin master
> ```

thanks, i just delete the code to avoid it, with out denoiser, i can generate voice by using nvidia's pre-trained model. however, my training's train loss is always oscillation around 0.4

**Comment by rafaelvalle** [comment]
Remember to run `Initialize submodule: git submodule init; git submodule update`
Assuming you have the same setup as the one in this implementation, you need to anneal the learning rate to further decrease the loss.

**Comment by orena1** [comment]
Thanks @rafaelvalle  but I think that in the waveglow submodule Denoiser is not there:
https://github.com/NVIDIA/waveglow/tree/4b1001fa3336a1184b8293745bb89b177457f09b

**Comment by vikrantsharma7** [comment]
The denoiser was added after the commit you mention.
Pull the latest master branch and you will find it.

**Comment by orena1** [comment]
I understand @vikrantsharma7 but as far as I see the git of tactron2 points to this commit
![image](https://user-images.githubusercontent.com/8983713/61202496-516d7300-a6f0-11e9-9ac4-f84b4f1e7e9f.png)

**Comment by vikrantsharma7** [comment]
Yes, it does and it hasn't been updated to use a commit that includes the denoiser, so you will need to manually pull it, or run inference without the denoiser.

**Comment by SomeUserName1** [comment]
can confirm that after
`git submodule init; git submodule update`
one needs also to 
`git pull origin master; git checkout 6188a1d106a1060336040db82f464d6441f39e21`
(If you dont checkout this commit there will be an AttributeError object NM does not have attribute cond_layer)
further the pretrained waveglow weights file needs to be renamed (cut off the _ljs_vX.pt)
Then it should work out of the box

**Comment by NoahDrisort** [comment]
I have a same problem, have you solve this, thank you

**Comment by ColeMurray** [comment]
Experienced the above issue. @SomeUserName1 suggestion to pull in the latest resolved this.
