### ISSUE TITLE
Inference result with wrong mel shape [1, 80, 1000]

### ISSUE THREAD

**Issue by daimon99** [NVIDIA/tacotron2#231]
I have trained the model 28000 turns with batch size 64.
But when i try to synthesize text : "Waveglow is really awesome!",
I get a 12 seconds sounds. The first 1 seconds is right, but the others are noises.
Is that because the model is not well trained?

```
>>> mel_outputs, mel_outputs_postnet, _, alignments = model.inference(sequence)
>>> print(mel_outputs.shape)
torch.Size([1, 80, 1000])
```

[Waveglow is really awesome.wav.zip](https://github.com/NVIDIA/tacotron2/files/3343706/Waveglow.is.really.awesome.wav.zip)

**Comment by NileZhou** [comment]
如果使用nvidia给的waveglow模型是不会有噪音的，只会是胡说一通。
请问你是用哪个数据集呢，我在ljspeech上，跑了五万步，可loss还在0.4，效果也很差

**Comment by daimon99** [comment]
你可以合成一个“Waveglow is really awesome!”这个看看吗？我合成出来是12秒音频。

**Comment by NileZhou** [comment]
> 你可以合成一个“Waveglow is really awesome!”这个看看吗？我合成出来是12秒音频。

[1, 80, 154], 这是我训练的tacotron2生成的梅尔谱的尺寸，然后用 nvidia给的waveglow_256channels.pt  合成是的读音是 witch with wedding ors??????
给出的图像也是乱的，不像nvidia的tacotron2_statedict.pt 模型，合成出来的图像是大致左下延申到右上的。
我也训练了waveglow的模型，目前用来从mel谱合成是可以的，不过噪声比较大
waveglow训练时的输出是这样的，不知道正常不
57180:  -5.971135139
57181:  -5.319574356
57182:  -5.024590492
57183:  -5.196775436
57184:  -5.096671104
57185:  -4.630523205
57186:  -5.423051834

**Comment by daimon99** [comment]
When I reduce the gate_theshhold to 0.001, it is ok now.

**Comment by daimon99** [comment]
我单独训练的waveglow，17万步。能很完美的根据 mel 还原声音。
tacotron2的这部分，我刚训练到2万步。还行啊。我的12秒是因为gate_threshhold的原因
