### ISSUE TITLE
Should we calculate mel spectrogram using amplitude or power ?

### ISSUE THREAD

**Issue by Yablon** [NVIDIA/tacotron2#236]
I learned on https://en.wikipedia.org/wiki/Mel-frequency_cepstrum that mel spectrogram should be calculated using power of the linear frequency magnitude. While in this repository, magnitude is directly used, is there any tricks in it ?
Many appreciates to the author of this repository ! I learned a lot.

**Comment by jasminsternkopf** [comment]
Hi @Yablon, I noticed you closed the issue on the same day you opened it, does that mean you found an answer to your question? I'm having the same question at the moment and would appreciate any help.
