### ISSUE TITLE
tensorboardX TypeError: Cannot handle this data type

### ISSUE THREAD

**Issue by hadaev8** [NVIDIA/tacotron2#238]
Code
https://colab.research.google.com/drive/1tUfEGU7_OqZzq9pmkHBX6GUDyy3zHm6x

Using tensorboardX==1.1 trigger another error
https://github.com/NVIDIA/tacotron2/issues/149#issuecomment-512647989

**Comment by batho2n** [comment]
I solve the ploblem using remove tensorboard package

> pip uninstall tensorboard

Do training processe after remove tensorboard...

**Comment by taekyun-lee** [comment]
In latest TensorboardX, default data format is "CHW" (I think it changed).
I solved this issue by changing data formats to "HWC". #239

**Comment by hadaev8** [comment]
Thanks

**Comment by mansur007** [comment]
> In latest TensorboardX, default data format is "CHW" (I think it changed).
> I solved this issue by changing data formats to "HWC". #239

Where can I change it? Thanks
