### ISSUE TITLE
CPU-inference memory leak

### ISSUE THREAD

**Issue by fxwderrick** [NVIDIA/tacotron2#242]
Hi all,
I modified the project code to enable only-cpu inference, by replacing `.cuda()` with `.cpu()`, as well as not using `.half()` datatype, adding `map_location=torch.device('cpu')` to `torch.load`. However, the memory leak might be a problem. When I load the tacotron2 and waveglow models, and keep generating waveform from text, the cpu memory will increase all the time. For GPU inference, `torch.cuda.empty_cache()` will be useful to collect garbage. However for cpu inference, I can hardly find an alternative approach to release the memory. Is there anyone who has experience with it.

**Comment by rafaelvalle** [comment]
You can do it in 2 steps:
1) Generate mels with tacotron and save them to disk
2) Load the mels saved to disk and decode them with waveglow

**Comment by fxwderrick** [comment]
@rafaelvalle That solves the problem. Thank you! Closing it.
