### ISSUE TITLE
How to make multispeaker tacotron2?

### ISSUE THREAD

**Issue by hadaev8** [NVIDIA/tacotron2#250]
I wanna try to train it on multiple datasets with multiple speakers, what changes should I make? Any guides/examples?

**Comment by asmodaay** [comment]
Try to use Tacotron GST

**Comment by rafaelvalle** [comment]
Add a speaker embedding layer and append the speaker embedding to the encoder outputs, replicating it over the time dimension. Note that you'll have to change the input dimension of your attention rnn.

**Comment by hadaev8** [comment]
@rafaelvalle 
What mean memory_lengths in decoder? Should I add +1 for speaker embedding?
Also, any eta for this realize? Like week or month?

**Comment by hadaev8** [comment]
Also is it ok im having a very huge loss (1-10k)?

**Comment by hadaev8** [comment]
Maybe I need to train more, or should not to start from one speaker checkpoint, but it produces the same voice with every speaker id.

**Comment by yxt132** [comment]
> Add a speaker embedding layer and append the speaker embedding to the encoder outputs, replicating it over the time dimension. Note that you'll have to change the input dimension of your attention rnn.
> 
> We're going to release Multispeaker Tacotron GST: stay tuned!

Hi Rafael, @rafaelvalle 

Do you have projected timeline when the Tacotron GST will be released? Looking forward to testing it out!

**Comment by rafaelvalle** [comment]
https://github.com/NVIDIA/mellotron
Our mellotron repo uses a Multispeaker Tacotron with GST.
