### ISSUE TITLE
Why not use the final mel output as the prenet input?

### ISSUE THREAD

**Issue by terryyizhong** [NVIDIA/tacotron2#268]
I have a question about the inference architecture of Tacotron2.
I know the paper use the mel of decoder output as the prenet input.
But Why not use the final mel output (decoder output combined with postnet output, which I think is closer to the ground truth mel) as the prenet input?

**Comment by Yeongtae** [comment]
After done autoregressive task in decoder, prenet step is computed, with a melspectrogram, not spectrum.

**Comment by terryyizhong** [comment]
> spectrum
Thanks for your reply. But I didn't get your point. I am not talking about spectrum.
In my understand of the paper, the output of Postnet is a residual mel spectrogram which add to decoder output to improve the mel spectrogram generate by decoder. And the input of prenet is also mel spectrogram. I am wondering why not use the mel spectrogram after improved.
Maybe is just for time saving?   @Yeongtae

**Comment by terryyizhong** [comment]
Did you mean the input of the Postnet  is the Full Mel spectrogram, not the one-frame mel spectrogram generate by the decoder?

**Comment by Yeongtae** [comment]
@terryyizhong 
Yes, exactly.

**Comment by terryyizhong** [comment]
> @terryyizhong
> Yes, exactly.

Thanks!
