### ISSUE TITLE
weird attention plot

### ISSUE THREAD

**Issue by lingjzhu** [NVIDIA/tacotron2#269]
Hi I am trianing the Tacotron2 model on Chinese. I use a phoneme based features as input and the model seems to converge rather quickly. While the synthesized output is intelligible with Griffin-Lim algoritm, the attention plots look rather strange. The alignment is not perfectly diagonal and there seems to be a gap toward the tail of alignment (images below). The things I change are replacing alphabets with Chinese phonemes and padding the EOS tokens. Besides, in the data, each sentence ends with a period. 

I have successfully replicated the LJ speech training and the attention is perferctly diagonal. So I think there must be something wrong here. Have anyone of you encountered such an issue before? Do you happen to have any advice? Thanks very much!

Step 1000
![1000](https://user-images.githubusercontent.com/7823218/65822634-a6138b00-e215-11e9-96fa-337545bb5061.png)
Step 20000
![20000](https://user-images.githubusercontent.com/7823218/65822635-ac096c00-e215-11e9-9c97-91520dc29526.png)
Step 22000
![22000](https://user-images.githubusercontent.com/7823218/65822642-baf01e80-e215-11e9-8cda-1aa11e0c7a37.png)
Step 29000
![29000](https://user-images.githubusercontent.com/7823218/65822639-b166b680-e215-11e9-8195-c5876463ba89.png)

**Comment by Yeongtae** [comment]
Are there silence at the end audio on your dataset?

**Comment by lingjzhu** [comment]
Thanks for your reply! I had removed the silence at the beginning and the end. I listened to several training samples, which all had the silence trimmed. The generated speech sounds OK but the attention plot does not look right. I was wondering if the model was stuck in some local minimum and could not get out. 

I retrained the model using the English tacotron as initialization. The alignment plot looks great at 1k steps. So this might have something to do with the initialization...

**Comment by Yeongtae** [comment]
Add silence audio which is 5 $\times$ hop_size. 
It will make learned attention alignments better.

**Comment by lingjzhu** [comment]
Oh thanks for the advice. Removing the silence may cause my problem then. I will try it tomorrow. Thanks!
But just out of curiosity, why adding silence will help? Isn't there silence padded by the model?

**Comment by Yeongtae** [comment]
check https://github.com/NVIDIA/tacotron2/issues/263

**Comment by lingjzhu** [comment]
Thank  you! With the pre-trained model, I was able to obtain perfect aligment this time! I will try silence padding at the end at next iteration of training. 
![sample_attention](https://user-images.githubusercontent.com/7823218/65905844-61136400-e38f-11e9-8535-efe7f4674294.png)

**Comment by SwordElucidator** [comment]
> Thank you! With the pre-trained model, I was able to obtain perfect aligment this time! I will try silence padding at the end at next iteration of training.
> ![sample_attention](https://user-images.githubusercontent.com/7823218/65905844-61136400-e38f-11e9-8535-efe7f4674294.png)

Wow, this looks great! I'm currently stuck with the bad training result on my Chinese dataset and would you like to share some ideas on preprocessing? Are you using pinyin or unicode? As words or as characters? 

Currently I'm working like this: `ta1 shui4 de2 ji2wei2 xiang1tian2 ,` ,   though i'm not sure whether i should use `ta1 shui4 de2 ji2 wei2 xiang1 tian2 ,` or else. Many thanks!

**Comment by lingjzhu** [comment]
> > Thank you! With the pre-trained model, I was able to obtain perfect aligment this time! I will try silence padding at the end at next iteration of training.
> > ![sample_attention](https://user-images.githubusercontent.com/7823218/65905844-61136400-e38f-11e9-8535-efe7f4674294.png)
> 
> Wow, this looks great! I'm currently stuck with the bad training result on my Chinese dataset and would you like to share some ideas on preprocessing? Are you using pinyin or unicode? As words or as characters?
> 
> Currently I'm working like this: `ta1 shui4 de2 ji2wei2 xiang1tian2 ,` , though i'm not sure whether i should use `ta1 shui4 de2 ji2 wei2 xiang1 tian2 ,` or else. Many thanks!

I used segmented pinyin like this: t a1 j i2 wei2 x iang1. In other words, I segment each pinyin syllable into consonants and vowels+tones.

**Comment by SwordElucidator** [comment]
@lingjzhu Sounds like a great idea! I'll try it and see what happens. Thank you :)

**Comment by leijue222** [comment]
@lingjzhu @SwordElucidator 

> I used segmented pinyin like this: t a1 j i2 wei2 x iang1. In other words, I segment each pinyin syllable into consonants and vowels+tones.

It is recommended to separate the tone numbers and the vowels, as they cause the matrix to be sparse.

By the way, is there any modification other than the data set? The pitch I got through training like this is still inaccurate.

------

I got it, I have changed  [cleaners](https://github.com/NVIDIA/tacotron2/blob/master/text/cleaners.py), but [symbols](https://github.com/NVIDIA/tacotron2/blob/185cd24e046cc1304b4f8e564734d2498c6e2e6f/text/symbols.py#L12) should have the number.
