### ISSUE TITLE
Why the pre-trained model's output quality is not as good as the provided samples?

### ISSUE THREAD

**Issue by h-shad** [NVIDIA/tacotron2#273]
Hi, thanks for this nice implementation.
I used the pre-trained model alongside the Griffin-Lim but the output quality is not as good as the samples you have provided [here](https://nv-adlr.github.io/WaveGlow). 
Why is this the case?
Thanks!

**Comment by rafaelvalle** [comment]
The samples provided on the link you shared are generated from real mel-spectrograms, not from Tacotron 2.

**Comment by h-shad** [comment]
Oh I see! Thank you @rafaelvalle for pointing this out.
I have gotten [this](http://vocaroo.com/i/s1e0wN41ybmf) output from the pre-trained model (with Griffin-Lim). Dose it sound reasonable to you?
Thanks in advance.
