### ISSUE TITLE
How to correctly apply griffin-lim vocoder?

### ISSUE THREAD

**Issue by Razcle** [NVIDIA/tacotron2#274]
Hi,

I wanted to add some example audio to the tensorboard during training to help monitor quality and so I thought I'd add this using griffin-lim.

One thing that I'm a little unclear about is how to get the linear spectrogram needed for griffin-lim from the mel spectrogram.

The mel-spectrogram is created by multiplying the magnitude part of the  linear-spectrogram by the mel-basis.  i.e mel_spec = torch.mm(mel_basis, magnitudes).

This seems to imply that to get back the linear spectrogram you should multiply the spectrogram by something like the pseudo-inverse of the mel-basis? But that isn't what seems to be done in the example.

Please could you help me with my misunderstanding.

many thanks!

**Comment by rafaelvalle** [comment]
https://github.com/NVIDIA/tacotron2/issues/41#issuecomment-397439290
