### ISSUE TITLE
Each time call taocotron2.inference(), I get different results.

### ISSUE THREAD

**Issue by wugi88** [NVIDIA/tacotron2#28]
Thank you for sharing great work.
 
Each time call taocotron2.inference(), I get different results.
If I understand correctly, I think it is due to dropout. Isn't it?

**Comment by rafaelvalle** [comment]
Yes. Please look at this issue: 
https://github.com/NVIDIA/tacotron2/issues/26

**Comment by wugi88** [comment]
Thank you.
I saw that issue. But, If I understand correctly there is one more dropout that doesn't return identity. (in Postnet)

-------------------
model.inference
-------------------
<bound method Tacotron2.inference of Tacotron2(
  (embedding): Embedding(80, 512)
  (encoder): Encoder(
    (dropout): Dropout(p=0.0)
 ....
  (postnet): Postnet(
    (dropout): Dropout(p=0.5)

**Comment by wugi88** [comment]
Thanks. I read that issue and understood it.

When I edited prenet's dropout like others dropout in same file, It returns same results when ever I call inference().

Is there any reason training is hardcoded in prenet's dropout?

I am training tacotron2 using Korean corpus, It works well.
But even though I used the same input, I sometimes got wrong pronunciation. So I made this issue.
