### ISSUE TITLE
unable to load waveGlow model to synthesize voice in infrence.ipyb

### ISSUE THREAD

**Issue by nimamoradi** [NVIDIA/tacotron2#281]
I trained tacotron model with my custom dataset and I want to  test its performance, but I am unable to load waveglow model using pytorch version "1.2.0"  version.<br>
here is the log
<pre><code>
Traceback (most recent call last):
  File "runner.py", line 35, in <module>
    waveglow = torch.load(waveglow_path,map_location='cpu')['model']
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.
</pre></code>
i test tacotron trained model with torch version <code>1.0.0</code> but it was unable to load it.
<br>
PS: <b> it think its versioning conflict problem but testing version 1.1.0 and 1.0.0 don't seam to reslove the problem

**Comment by mingfengwuye** [comment]
s = pickle.load(f, encoding='latin1') add encoding param to this function
