### ISSUE TITLE
ModuleNotFoundError: No module named 'denoiser'

### ISSUE THREAD

**Issue by gandolfxu** [NVIDIA/tacotron2#287]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-1e40ea2a3544> in <module>
     16 from train import load_model
     17 from text import text_to_sequence
---> 18 from denoiser import Denoiser

ModuleNotFoundError: No module named 'denoiser'

**Comment by CookiePPP** [comment]
Copy & Paste from WaveGlow?

**Comment by rafaelvalle** [comment]
``Initialize submodule: git submodule init; git submodule update``
