### ISSUE TITLE
Why gate loss calculated like this?

### ISSUE THREAD

**Issue by hadaev8** [NVIDIA/tacotron2#289]
https://github.com/NVIDIA/tacotron2/blob/a513db50d05ff3b2275b4e6b086b8b0c070a715f/loss_function.py#L15
I mean why it reshaped?

**Comment by rafaelvalle** [comment]
It was a requirement of the pytorch version.
Iirc this reshaping is not needed in recent pytorch version.

**Comment by hadaev8** [comment]
Thx
