### ISSUE TITLE
problem on long sentence (max 3 minutes 23 seconds)

### ISSUE THREAD

**Issue by yfliao** [NVIDIA/tacotron2#292]
Dear All,

If I have long sentence (max 3 minutes 23 seconds and at average 2 minutes), how could I make it work? The program always reports "CUDA out of memory" on two K-80 with 12G rams.

I have try to reduce the model and batch size, but it didn't solve the problem so far. Besides, I got a "WARNING:root:NaN or Inf found in input tensor." message in the first iteration and sometime "Grad Norm:  inf".

Thanks for your help!

Best Regards,
Yuanfu

FYI: Here is my current setting
        ################################
        # Model Parameters             #
        ################################
        n_symbols=len(symbols),
        symbols_embedding_dim=16,

        # Encoder parameters
        encoder_kernel_size=5,
        encoder_n_convolutions=3,
        encoder_embedding_dim=16,

        # Decoder parameters
        n_frames_per_step=1,  # currently only 1 is supported
        decoder_rnn_dim=128,
        prenet_dim=16,
        max_decoder_steps=1000,
        gate_threshold=0.5,
        p_attention_dropout=0.1,
        p_decoder_dropout=0.1,

        # Attention parameters
        attention_rnn_dim=128,
        attention_dim=16,

        # Location Layer parameters
        attention_location_n_filters=16,
        attention_location_kernel_size=31,

        # Mel-post processing network parameters
        postnet_embedding_dim=16,
        postnet_kernel_size=5,
        postnet_n_convolutions=5,

**Comment by rafaelvalle** [comment]
Take advantage of language and split the phrase at punctuations.
