### ISSUE TITLE
Plan to integrate with nv-wavenet?

### ISSUE THREAD

**Issue by neverjoe** [NVIDIA/tacotron2#3]
I think integrating taco2 with nv-wavenet still is a long way, first thing i think nv-wavenet should support mol, not just 8bit.

**Comment by neverjoe** [comment]
Great work!
Can u share some wav sample of your full stack tts system(8 bit nv-wavenet)?

**Comment by rafaelvalle** [comment]
Not yet but soon. We're currently working on another release.

**Comment by glennglennglenn** [comment]
@rafaelvalle How long do you think it will be before the integration with nv-wavenet is released? How is the voice quality with that integration?

**Comment by rafaelvalle** [comment]
Pytorch bindings for 8-bit mulaw nv-wavenet should be out this week.

**Comment by neverjoe** [comment]
nice work!@rafaelvalle, Can I use r9y9's wavenet arch of 8-bit mulaw with your work?

**Comment by rafaelvalle** [comment]
It should be possible. You'll need to load the weights onto the PyTorch bindings.

**Comment by glennglennglenn** [comment]
@rafaelvalle are the Pytorch bindings for 8-bit mulaw nv-wavenet going to be integrated into this repo? Or will we need to figure out how to get them to work together?

**Comment by rafaelvalle** [comment]
Integration is simple: just provide mel-spectrograms as input to the nv-wavenet pytorch bindings.
The pull request is here:
https://github.com/NVIDIA/nv-wavenet/pull/7/files

**Comment by rafaelvalle** [comment]
For a follow-up with this issue please use this https://github.com/NVIDIA/nv-wavenet/pull/7/files where the pytorch bindings are being released.
Closing.

**Comment by PetrochukM** [comment]
@rafaelvalle Reposted!

**Comment by viogoes** [comment]
@rafaelvalle  It should be possible. You'll need to load the weights onto the PyTorch bindings.
How to load the weights?

**Comment by rafaelvalle** [comment]
@viogoes please ask this question on the nv-wavenet repo.
