### ISSUE TITLE
Punctuation misalignment problem.

### ISSUE THREAD

**Issue by chazo1994** [NVIDIA/tacotron2#314]
Hi, I'm Thinh,
I'm training tacotron2 model with 27h of audio recording. I used phoneme embedding for represent input text. But our model has misalignment for punctuation position. I train two model: The first one, the punctuation still stored as character (ex: '.' or ';'), and the second, I convert all punctuation into pau phoneme representation. Both models above are misalignment at the punctuation position.
Any suggestions on how to train better?

![punctuation_misaligment](https://user-images.githubusercontent.com/17020334/76853541-11aeea80-6880-11ea-8b95-c976baff9422.png)

**Comment by NTT123** [comment]
You can checkout this repository https://github.com/mozilla/TTS which uses Graves' monotonic attention mechanism. The attention mechanism is similar to https://google.github.io/tacotron/publications/location_relative_attention/index.html

Alternatively, you can checkout https://github.com/fatchord/WaveRNN 
which reduces sequence's length by a factor of 4 or so, that helps very much in training attention mechanism.

**Comment by chazo1994** [comment]
> You can checkout this repository https://github.com/mozilla/TTS which uses Graves' monotonic attention mechanism. The attention mechanism is similar to https://google.github.io/tacotron/publications/location_relative_attention/index.html
> 
> Alternatively, you can checkout https://github.com/fatchord/WaveRNN
> which reduces sequence's length by a factor of 4 or so, that helps very much in training attention mechanism.

Thank for your suggestion. But I still want to know the reason of my problems. One special thing in my data is that each punctuation is a silent which padded to zero. Back to your suggestion, 
can that solution solve the cause of the problem? I saw that my tacotron2 model have good alignment for sentences without punctuation.

**Comment by NTT123** [comment]
This is a general attention problem. *My guess* is that when the network sees a ".", it cannot predict how long the *silent* will last (because it varies very much). Because of that it will need other information to be able to predict the length of the silent segment.  So, the network will try to read other characters to predict the silent segment. In short, the network try to *overfit* the dataset to predict silent segments.

*Location relative attention* guarantees that the network only attends to *surrounding* characters of ".", it should solve this attention problem, however, it will be more unstable/harder to train.

**Comment by chazo1994** [comment]
> 

A great answer, thank you so much. I will try some method to guide Network predict the silient segment.

**Comment by chazo1994** [comment]
The season of this problems is my data has mismatch transcriptions.

**Comment by NoahDrisort** [comment]
> Hi, I'm Thinh,
> I'm training tacotron2 model with 27h of audio recording. I used phoneme embedding for represent input text. But our model has misalignment for punctuation position. I train two model: The first one, the punctuation still stored as character (ex: '.' or ';'), and the second, I convert all punctuation into pau phoneme representation. Both models above are misalignment at the punctuation position.
> Any suggestions on how to train better?
> 
> ![punctuation_misaligment](https://user-images.githubusercontent.com/17020334/76853541-11aeea80-6880-11ea-8b95-c976baff9422.png)

Can you share how you deal with "phoneme embedding", do you change this in text symbol or anywhere? And what type of phoneme are you using?

**Comment by chazo1994** [comment]
> > Hi, I'm Thinh,
> > I'm training tacotron2 model with 27h of audio recording. I used phoneme embedding for represent input text. But our model has misalignment for punctuation position. I train two model: The first one, the punctuation still stored as character (ex: '.' or ';'), and the second, I convert all punctuation into pau phoneme representation. Both models above are misalignment at the punctuation position.
> > Any suggestions on how to train better?
> > ![punctuation_misaligment](https://user-images.githubusercontent.com/17020334/76853541-11aeea80-6880-11ea-8b95-c976baff9422.png)
> 
> Can you share how you deal with "phoneme embedding", do you change this in text symbol or anywhere? And what type of phoneme are you using?

I use Phonetic dictionary to convert grapheme to phoneme and I change symbols to include my phonemes, punctuation and number.

**Comment by NoahDrisort** [comment]
@chazo1994 Can you share your symbols.py file? I still can not imagine how phonemes are represented. Also about punctuation, you have "padded to zero", do you keep the set _punctuation as in NVIDIA repo.

**Comment by chazo1994** [comment]
> padded to zero
I'm sorry for my late reply, to represent phonemes based you need a phonetic dictionary. I cannot share my symbol.py file because of my company policy. In addition, I keep the set _punctuation as NVIDIA repo.

**Comment by chazo1994** [comment]
> padded to zero
I'm sorry for my late reply, to represent phonemes based you need a phonetic dictionary. I cannot share my symbol.py file because of my company policy. In addition, I keep the set _punctuation as NVIDIA repo.

**Comment by chazo1994** [comment]
> This is a general attention problem. _My guess_ is that when the network sees a ".", it cannot predict how long the _silent_ will last (because it varies very much). Because of that it will need other information to be able to predict the length of the silent segment. So, the network will try to read other characters to predict the silent segment. In short, the network try to _overfit_ the dataset to predict silent segments.
> 
> _Location relative attention_ guarantees that the network only attends to _surrounding_ characters of ".", it should solve this attention problem, however, it will be more unstable/harder to train.

Do you know and repo or fork which implement location relative attention for tacotron2?

**Comment by EuphoriaCelestial** [comment]
@chazo1994 Hi, glad to hear you have solved your problem with dataset; can it be shared? It would be great for other researchers
