### ISSUE TITLE
Wrong target mel spectrogram

### ISSUE THREAD

**Issue by EunminKim** [NVIDIA/tacotron2#316]
Thank you for sharing the amazing repo.
I'm trying to train the model for korean language.
When I looked through the tensor board, I found the target spectrogram to be weird.
(In the case of ljs, it is clear)
Do you know why this is happening?

My training data is kss data
This file is in mono format with a 22050 sampling rate.

![mel_target](https://user-images.githubusercontent.com/8408055/77147440-94c67f80-6ad0-11ea-894e-6a33a6da8fc5.png)

[1_0000.wav.zip](https://github.com/NVIDIA/tacotron2/files/4358519/1_0000.wav.zip)

**Comment by EunminKim** [comment]
There seems to be a problem with the resampling process.
my data set became normal after saving it to PCM 16bit mono through app audicity.

**Comment by luvwinnie** [comment]
@EunminKim could you provide an example by using the soundfile library to convert to target 22050Hz?

**Comment by luvwinnie** [comment]
I have same issues with my spectrogram.
I convert 48000Hz to 22050Hz by using the librosa resample.
@EunminKim could you show an example of how to fix this problem?
i use the below code to convert

```
from librosa.core import stft, load, istft, resample
import soundfile as sf
import numpy as np

target_sr = 22050
for path in paths:
    y,org_sr = load(path)
    new_y = resample(y,org_sr,target_sr,scale=True)
    folder_name,_,filename = path.split("/")[-3:]
    if not os.path.exists(f"{basepath}{folder_name}/wav"):
        os.makedirs(f"{basepath}{folder_name}/wav")
    output_path = basepath+"/".join(path.split("/")[-3:])
    print(output_path)
    y = np.array(new_y*32768,dtype="int16")
    sf.write(output_path,y,target_sr,"PCM_16")
```

**Comment by EunminKim** [comment]
@luvwinnie Hi. I'm using a converter like below.

def down_sample(input_wav, resample_sr):
    if os.path.isfile(input_wav):
        return
    _, filename = os.path.split(input_wav)
    y, sr = librosa.load(input_wav)
    sf.write('./resampled/' + filename, y, resample_sr, format='WAV', endian='LITTLE', subtype='PCM_16')

target_sr = 22050
down_sample('./test.wav', target_sr)

**Comment by luvwinnie** [comment]
@EunminKim Thank you for replying! It seems like my resampling was wrong.

**Comment by jodumagpi** [comment]
I'm wondering how should the target mel spectrograms look like? I just tried to generate spectrograms for both KSS and LJ datasets using the functions available in this implementation and they kind of look the same (very sparse). 

KSS Dataset:
![image](https://user-images.githubusercontent.com/24381086/114649204-047e5c80-9d1b-11eb-9041-4d399a9164d7.png)

LJ Dataset:
![image](https://user-images.githubusercontent.com/24381086/114649225-0fd18800-9d1b-11eb-9b4c-c5c5c7a1c3ef.png)

**Comment by eunminkeem** [comment]
Hi
To see successful mel spec, Please refer to tensorboard samples in readme.
=> https://github.com/NVIDIA/tacotron2/blob/master/tensorboard.png
These spectrograms you uploaded were not properly extracted, It should be clearer and a lot of things should be visible like a rib bone.
How about doing resample using soundfile library on python?
