### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by Dekakhrone** [NVIDIA/tacotron2#318]
Hello! First of all, thanks for such an incredible job!

I am here to tell you that there are some version mismatches:
- the inference example contains the use of denoiser, while the waveglow submodule leads to the 4b1001f commit, which does not contain it;
- <s>the latest waveglow model "waveglow_256channels_ljs_v2.pt" is not compatible with the last three commits in the main branch due to fusing cond layers (probably I should write it there, not here, but still).</s> - solved

**Comment by ArtemisZGL** [comment]
Hello, do you have some methods to fix that problem ? I clone the newest version of tacotron2 and waveglow. And i try to run the jupyter for inference,  but showing the error 'AttributeError: 'WN' object has no attribute 'cond_layer'' when loading waveglow_256channels_ljs_v2.pt. Should I change the version of waveglow code or the checkpoint?

**Comment by Dekakhrone** [comment]
@ArtemisZGL hello! Switching waveglow to commit 6188a1d worked for me.

**Comment by ArtemisZGL** [comment]
@Dekakhrone Thanks for your reply, but after I change to 6188a1d106a1060336040db82f464d6441f39e21, i still got the error "'WN' object has no attribute 'cond_layer'", did you download the checkpoint from the tacotron2 README?

**Comment by Dekakhrone** [comment]
@ArtemisZGL no, I took checkpoint from [here ](https://ngc.nvidia.com/catalog/models/nvidia:waveglow_ljs_256channels/files). As far as I understand this is their latest model.

**Comment by ArtemisZGL** [comment]
@Dekakhrone thanks, I have fixed the problem !

**Comment by Dekakhrone** [comment]
@ArtemisZGL you're welcome!

**Comment by Dekakhrone** [comment]
The problem with weights for waveglow is not actual anymore, thanks.

**Comment by rafaelvalle** [comment]
The older model has to be updated with `convert_model.py`
`python tacotron2/waveglow/convert_model.py waveglow_256channels_v4.pt waveglow_256channels_v4_new.pt`

**Comment by Dekakhrone** [comment]
@rafaelvalle great, thanks! Closing the issue.

**Comment by titospadini** [comment]
@rafaelvalle unfortunately, I still have this error, even after apply the convert_model.py.
