### ISSUE TITLE
Distributed setup bug

### ISSUE THREAD

**Issue by IwraStudios** [NVIDIA/tacotron2#32]
I got this error while executing the distributed setup described in README:
```
"./distributed.py", line 95, in allreduce_hook
AttributeError: 'Parameter' object has no attribute '_execution_engine'
```
With a bit of searching it seems to be related to: https://github.com/pytorch/pytorch/commit/6b3a4637d6e87a543b3df6edb825c07d7dabe611#diff-28369e7c07a82d014949812f10d9a188

(And it also seems the same problem is/was in https://github.com/NVIDIA/sentiment-discovery/blob/master/model/distributed.py)

**Comment by rafaelvalle** [comment]
@IwraStudios thanks for sharing.
@raulpuric any thoughts on this given that we had a similar problem in our sentiment-discovery repo?

**Comment by IwraStudios** [comment]
@rafaelvalle Found the issue from sentiment-discovery on the topic https://github.com/NVIDIA/sentiment-discovery/issues/16

**Comment by rafaelvalle** [comment]
@IwraStudios can you share the full error trace?

**Comment by IwraStudios** [comment]
Ah right sorry about that
```
Traceback (most recent call last):
  File "train.py", line 291, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 222, in train
    optimizer.backward(loss)
  File "/home/null/nv-wavenet/pytorch/tacotron2/fp16_optimizer.py", line 362, in backward
    self.loss_scaler.backward(loss.float())
  File "/home/null/nv-wavenet/pytorch/tacotron2/loss_scaler.py", line 80, in backward
    scaled_loss.backward()
  File "/home/null/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/null/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/null/nv-wavenet/pytorch/tacotron2/distributed.py", line 88, in allreduce_params
    coalesced = _flatten_dense_tensors(grads)
  File "/home/null/nv-wavenet/pytorch/tacotron2/distributed.py", line 19, in _flatten_dense_tensors
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
RuntimeError: Expected a Tensor of type torch.cuda.HalfTensor but found a type torch.cuda.FloatTensor for sequence element 3  in sequence argument at position #1 'tensors'
```

**Comment by rafaelvalle** [comment]
@IwraStudios thank you. we currently do not have the cycles to work on fixing this bug.
If you're ok with using DistributedDataParallel without FP16, just disable FP16.

**Comment by IwraStudios** [comment]
Alright, I'll disable it for now.
Shall I close the issue or do you want to keep it open until fp16 gets fixed?

**Comment by rafaelvalle** [comment]
Let's keep it open as a record that the issue has to be solved!

**Comment by yhgon** [comment]
@IwraStudios 

One solution for   distributed FP16 training for Tacotron2 would be use NGC:18.03-py3  and simple patch.
I already build docker images you would just use `docker pull hryu/pytorch:t2-2` it is base on NGC 18.03 which based on  pytorch 0.3 and APEX patch. see detail [Dockerbuild](https://github.com/yhgon/tacotron2/blob/master/Dockerfile) file. after that, you need to implement simple patch for source code[ngc-patch for pytorch 0.3](https://github.com/NVIDIA/tacotron2/compare/master...yhgon:ngc-patch#diff-93ff136fae812392eb0f68d1ce89b7feR471) this patch don't support pytorch 0.4. so it is just temporal solution. 

detail instruction are in [readme file](https://github.com/yhgon/tacotron2/tree/ngc-patch)

**Comment by yhgon** [comment]
@IwraStudios  close this bug. 

I check FP16 training work well in NGC 18.06-py3 with below method. 

I check this is solved with below method. 
replace current distributed.py with new apex distributed.py 
(https://raw.githubusercontent.com/NVIDIA/apex/master/apex/parallel/distributed.py)

**Comment by jferrer21** [comment]
@yhgon 

Do you know (estimate) how long would take to train nv-wavenet with LJSpeech dataset and 
 1 Tesla V100 GPU?

**Comment by hdmjdp** [comment]
@IwraStudios @yhgon  I think you can just " flat = torch.cat([t.half().contiguous().view(-1) for t in tensors], dim=0)" to fix this.
