### ISSUE TITLE
How to save audio file after run inference?

### ISSUE THREAD

**Issue by EuphoriaCelestial** [NVIDIA/tacotron2#320]
Hi, I finished setup Jupyter notebook and run inference of Tacotron 2. How can I convert Jupyter code to normal Python code and save the audio result into .mp3 or .wav files?

**Comment by quangtt2016** [comment]
jupyter nbconvert --to script [YOUR_NOTEBOOK].ipynb

**Comment by EuphoriaCelestial** [comment]
@quangtt2016 thank you, I can convert it to .py file now. How about the save file ?

**Comment by quangtt2016** [comment]
audio = ipd.Audio(audio_denoised.cpu().numpy(), rate=hparams.sampling_rate)
audio.export(file_name_mp3, format="mp3", bitrate="64k")

**Comment by EuphoriaCelestial** [comment]
it return this error:
```
/media/hangtg/Data/tacotron2-origin/tacotron2/inference.py in <module>
     80 # export audio file
     81 audio = ipd.Audio(audio_denoised.cpu().numpy(), rate=hparams.sampling_rate)
---> 82 audio.export('output', format="mp3", bitrate="64k")
     83 
     84 

AttributeError: 'Audio' object has no attribute 'export'
```

**Comment by quangtt2016** [comment]
I changed the code above.
Here is another example from waveglow:
https://github.com/NVIDIA/waveglow/blob/4b1001fa3336a1184b8293745bb89b177457f09b/inference.py#L55

**Comment by DDeng-Z** [comment]
I changed my file according to the above,but it still tells me that it has some errors.Thanks a lot, if you can give me your changed code of inference.py , my emil address is 2693963616@qq.com.

**Comment by Truong-Thanh-Quang** [comment]
Please show the error detail.

**Comment by evelynyhc** [comment]
> I changed the code above.
> Here is another example from waveglow:
> https://github.com/NVIDIA/waveglow/blob/4b1001fa3336a1184b8293745bb89b177457f09b/inference.py#L55

hello, i run the code that you provided, but when i listen the audio, i found it have no sound, how can i fix it now?

**Comment by Truong-Thanh-Quang** [comment]
> > I changed the code above.
> > Here is another example from waveglow:
> > https://github.com/NVIDIA/waveglow/blob/4b1001fa3336a1184b8293745bb89b177457f09b/inference.py#L55
> 
> hello, i run the code that you provided, but when i listen the audio, i found it have no sound, how can i fix it now?

It is not related to the writing audio function.
Please check your data.
Another way, you can run in Jupiter and listen the result.

**Comment by bthiban** [comment]
`audio = waveglow.infer(mel_outputs_postnet, sigma=sigma);`
`sf.write('bira.wav', audio[0].data.cpu().numpy().astype(np.float32), hparams.sampling_rate)`
