### ISSUE TITLE
why can use Phoneme as input for the pretrain model?

### ISSUE THREAD

**Issue by ArtemisZGL** [NVIDIA/tacotron2#329]
I found the symbol in the original code has Phoneme. And When I use Phoneme as input to infer using the published checkpoint, it can work well. But I train the model for myself, and use Phoneme as input seems not work. And I can't find the english Grapheme to Phoneme conversion in the code. So I guess maybe the training data have both the Phoneme and Grapheme as text ? Did I miss something ?

**Comment by AppalachianWine** [comment]
This model uses char embedding.

**Comment by rafaelvalle** [comment]
@ArtemisZGL You can use the grapheme to phoneme pipeline in [Flowtron's repo](https://github.com/NVIDIA/flowtron/)
The Tacotron 2 we shared was trained both on graphemes and phonemes, hence the ability to perform inference with phonemes.
