### ISSUE TITLE
Cant load waveglow checkpoint into inference code even after convert

### ISSUE THREAD

**Issue by EuphoriaCelestial** [NVIDIA/tacotron2#330]
I have trained a new waveglow model for my language, but I cant load it into Tacotron2 `inference.ipynb` file to run test. It return this error:
`AttributeError: 'WN' object has no attribute 'cond_layers'`

I tried convert the checkpoint using `convert_model.py` file in `waveglow` folder but it still raise the same error

**Comment by TotzkePaul** [comment]
Which submodule are you using waveglow@4b1001f or waveglow@2fd4e63? 

What versions are you models/checkpoints? 

I just downloaded waveglow to it own folder and its saving headaches.  

https://github.com/NVIDIA/tacotron2/issues/333

**Comment by EuphoriaCelestial** [comment]
> Which submodule are you using waveglow@4b1001f or waveglow@2fd4e63?
> What versions are you models/checkpoints?

I dont know, how to check for those informations?

> I just downloaded waveglow to it own folder and its saving headaches.

yea, I am using pre-trained model, it working fine. But I want to re-train to see if it will imporve the synthesize performance or output audio quality, because my Tacotron model is in another language

**Comment by rafaelvalle** [comment]
@EuphoriaCelestial Please try updating your Tacotron 2 repo.
