### ISSUE TITLE
[FileNotFoundError] While more than 60 train data lines

### ISSUE THREAD

**Issue by ksaidin** [NVIDIA/tacotron2#334]
When I run train.py, it only works when I have less than 60 lines in my training txt but when it is more it gives some **random** line:

FileNotFoundError: [Errno 2] No such file or directory: 'audio/22.wav'

But that audio/22.wav was no problem when there were less lines in the training txt

What is this mystery? Thanks beforehand.

**Comment by EuphoriaCelestial** [comment]
I have encountered this an error similar to this before, it keep reporting a file in one exactly line in filelist  is causing problem. It take me a whole morning debug, found out nothing, so I go out for lunch, and when I return, it suddenly worked. Really confusing.

**Comment by ksaidin** [comment]
I've imitated exactly how the default LJ Speech dataset folders sits: ljs_dataset_folder/wavs structure (folder names, file names... everything)

Now it works, but I don't know why.
