### ISSUE TITLE
The paging file is too small for this operation to complete.

### ISSUE THREAD

**Issue by ksaidin** [NVIDIA/tacotron2#335]
Windows 10 automatically manages the pagefile for your computer's configuration and the amount of RAM present in it. So, it automatically allocates 12GB virtual memory for my 8GB RAM.

Train.py was trying to save checkpoint_19000, and it returns;

Train loss 19000 0.285415 Grad Norm 0.350990 2.25s/it
Traceback (most recent call last):
  ........................
  anaconda3\envs\nvidia2\lib\imp.py", line 343, in load_dynamic return _load(spec)
**ImportError: DLL load failed: The paging file is too small for this operation to complete.**

So how much vmemory/pagesize you guys set while training?

**Comment by ksaidin** [comment]
I guess this was a one-off error. I left vmemory setting as it was and I've been training various datasets since then. I was really pushing the limits but never again failed to load dll.

**Comment by gitttsummm** [comment]
Hi.  Seeing that it seems you're making good progress training your datasets, is there somewhere I can message you about a few questions regarding your setup?

**Comment by ksaidin** [comment]
Hello, ksaidinmi-at-gmail it is.
