### ISSUE TITLE
TypeError: ~ (operator.invert) is only implemented on byte tensors

### ISSUE THREAD

**Issue by Franek18** [NVIDIA/tacotron2#337]
Hi!
During training I got this error

> python train.py --output_directory=outdir --log_directory=logdir
> WARNING:tensorflow:
> The TensorFlow contrib module will not be included in TensorFlow 2.0.
> For more information, please see:
>   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
>   * https://github.com/tensorflow/addons
>   * https://github.com/tensorflow/io (for I/O related ops)
> If you depend on functionality not listed there, please file an issue.
> 
> FP16 Run: False
> Dynamic Loss Scaling: True
> Distributed Run: False
> cuDNN Enabled: True
> cuDNN Benchmark: False
> Epoch: 0
> Traceback (most recent call last):
>   File "train.py", line 290, in <module>
>     args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
>   File "train.py", line 215, in train
>     y_pred = model(x)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 531, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/tacotron2/model.py", line 508, in forward
>     encoder_outputs, mels, memory_lengths=text_lengths)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 531, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/tacotron2/model.py", line 402, in forward
>     memory, mask=~get_mask_from_lengths(memory_lengths))
> TypeError: ~ (operator.invert) is only implemented on byte tensors

I ran this in docker container configured with Dockerfile from the repo and installed all libraries from requirements.txt but with small changes due to occuring errors:
+ _matplotlib 2.1.0 ==> matplotlib 3.2.1_
+ _numpy 1.13.3 ==> numpy 1.16.0_
+ plus _future packet_

Does anyone have/had this problem?

Regards
Franek

**Comment by ksaidin** [comment]
Which version of pytorch you have?

**Comment by Franek18** [comment]
@ksaidin Good point, I resolve this by installing newer version of pytorch. I will close this issue.
