### ISSUE TITLE
compile error!

### ISSUE THREAD

**Issue by NewEricWang** [NVIDIA/tacotron2#34]
Hi, When I run "sudo pip install -r requirements.txt", I get an error " Could not find a version that satisfies the requirement torch==0.2.0.post3" . I successfully install pytorch by anaconda, command likes "sudo ./bin/conda install pytorch torchvision -c pytorch".  My python's version is 2.7 in anaconda. How can I resolve the error?

**Comment by ZuoChenFttS** [comment]
try to remove the line 'torch==0.2.0.post3' in requirements.txt?

**Comment by rafaelvalle** [comment]
@NewEricWang, please try what @ZuoChenFttS and let us know how it goes.

**Comment by NewEricWang** [comment]
@rafaelvalle ， @ZuoChenFttS ， Thank you! I have changed  "torch==0.2.0.post3"  to "torch==0.4.0", then the compile is successful. 
But when I run train.py using the command "/usr/bin/python train.py --output_directory=works --log_directory=works/log" , I get another error "RuntimeError: torch/csrc/autograd/variable.cpp:115: get_grad_fn: Assertion `output_nr == 0` failed.". Could you give me some hints?

**Comment by rafaelvalle** [comment]
@NewEricWang: What caused and how did you fix the `output_nr == 0` error?
