### ISSUE TITLE
phoneme embedding or char embedding?

### ISSUE THREAD

**Issue by xxoospring** [NVIDIA/tacotron2#340]
I've done three experiments about the embedding strategy: 1) text sequence input，2) phoneme sequence input，3) phoneme input,
1） and 2) are char-level embedding，but 3) is phoneme embedding，below is the modify of "symbols.py" of experiment 3):
```
phoneme_set = ['AA0', 'AA1', 'AA2', 'AE0', 'AE1', 'AE2', 'AH0', 'AH1', 'AH2', 'AO0', 'AO1',
               'AO2', 'AW0', 'AW1', 'AW2', 'AY0', 'AY1', 'AY2', 'B', 'CH', 'D', 'DH', 'EH0',
               'EH1', 'EH2', 'ER0', 'ER1', 'ER2', 'EY0', 'EY1', 'EY2', 'F', 'G', 'HH', 'IH0',
               'IH1', 'IH2', 'IY0', 'IY1', 'IY2', 'JH', 'K', 'L', 'M', 'N', 'NG', 'OW0', 'OW1',
               'OW2', 'OY0', 'OY1', 'OY2', 'P', 'R', 'S', 'SH', 'T', 'TH', 'UH0', 'UH1', 'UH2',
               'UW0', 'UW1', 'UW2', 'V', 'W', 'Y', 'Z', 'ZH', 'sil']

symbols = [_pad] + list(_punctuation) + phoneme_set
``` 
but I cant get a nomal aligment when do experiment 3) training even at 60 epoch , it was normal in experiment 1) and 2) at epoch 30 . 
![image](https://user-images.githubusercontent.com/21218850/80297445-952ff580-87b5-11ea-9933-134fac804e8b.png)

**Comment by AppalachianWine** [comment]
Hi, I encountered the same problem, char embedding alignment is normal, when I changed from char embedding to phoneme embedding, the alignment I get is a very bright horizontal line, is there any information that can be shared?

**Comment by xxoospring** [comment]
> Hi, I encountered the same problem, char embedding alignment is normal, when I changed from char embedding to phoneme embedding, the alignment I get is a very bright horizontal line, is there any information that can be shared?
phoneme embedding will be normal around at 70 epoch, this is much longer than char embedding(about 30 epoch). @AppalachianWine just wait

**Comment by evelynyhc** [comment]
hello, I'm a beginner in audio. Is there anything else changed with phoneme training? What does the training input look like?
