### ISSUE TITLE
Unstable result

### ISSUE THREAD

**Issue by tdplaza** [NVIDIA/tacotron2#345]
I have trained this repo with 13+ hours of Korean speech, about 1600 epochs.

The synthesized results are not stable,  sometime the model generates meaningless audio (with some . 
like this:
[111.zip](https://github.com/NVIDIA/tacotron2/files/4597209/111.zip)
(it should stop at first  or 2nd second, but it does not)

Sometime it could not synthesize the sentence completely like this:
[222.zip](https://github.com/NVIDIA/tacotron2/files/4597263/222.zip)

Could someone please tell me what is the problem here? I think the problem is at attention alignment, but don't know how to fix this. 
Any suggestion is highly appreciated.  
Thank you.

**Comment by ksaidin** [comment]
Check [this one](https://github.com/NVIDIA/tacotron2/issues/174#issuecomment-485591691) out for same problem. 

Also, trimming and adding some silence with [preprocessing audio files](https://github.com/NVIDIA/tacotron2/issues/263#issuecomment-529749345) help a lot.

**Comment by tdplaza** [comment]
> Check [this one](https://github.com/NVIDIA/tacotron2/issues/174#issuecomment-485591691) out for the same problem.
> 
> Also, trimming and adding some silence in the end with [preprocessing audio files](https://github.com/NVIDIA/tacotron2/issues/263#issuecomment-529749345) helps a lot.

Thank you so much, sir.
