### ISSUE TITLE
Warmstart via a different language

### ISSUE THREAD

**Issue by fatihkiralioglu** [NVIDIA/tacotron2#349]
Hi,
Is it possible to use warmstart feature on a language other than English for faster convergence? Using LJSpeech pretrained model as a base, I like to know if we can get feasible results if we try to train a new model of a different speaker and a different language. 
Best Regards.

**Comment by ksaidin** [comment]
Yes, check [this one](https://github.com/NVIDIA/tacotron2/issues/321#issuecomment-603894212).

**Comment by fatihkiralioglu** [comment]
Thanks, @ksaidin ,
What if I want to train a new model for Spanish using English pretrained model as a base?

**Comment by ksaidin** [comment]
Why don't you give a try? It works even for russian language with its cyrillic letters. Make sure you are warm starting when training with [English pretrained tacotron 2 model](https://github.com/NVIDIA/tacotron2#training-using-a-pre-trained-model).

**Comment by fatihkiralioglu** [comment]
Thanks, I will try right away
