### ISSUE TITLE
inference failed 

### ISSUE THREAD

**Issue by maozhiqiang** [NVIDIA/tacotron2#35]
when eval the model ! has a  error！

RuntimeError                              Traceback (most recent call last)
<ipython-input-4-84fac00df448> in <module>()
      5 except:
      6     pass
----> 7 model.load_state_dict({k.replace('module.',''):v for k,v in torch.load(checkpoint_path)['state_dict'].items()})
      8 _ = model.eval()

/home/btows/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    719         if len(error_msgs) > 0:
    720             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 721                                self.__class__.__name__, "\n\t".join(error_msgs)))
    722 
    723     def parameters(self):

RuntimeError: Error(s) in loading state_dict for Tacotron2:
	Unexpected key(s) in state_dict: "encoder.convolutions.0.1.num_batches_tracked", "encoder.convolutions.1.1.num_batches_tracked", "encoder.convolutions.2.1.num_batches_tracked", "postnet.convolutions.0.1.num_batches_tracked", "postnet.convolutions.1.1.num_batches_tracked", "postnet.convolutions.2.1.num_batches_tracked", "postnet.convolutions.3.1.num_batches_tracked", "postnet.convolutions.4.1.num_batches_tracked".

**Comment by rafaelvalle** [comment]
I think this is a pytorch version related problem. 
What is your pytorch version?
Are you running the code from master without modifications?

**Comment by maozhiqiang** [comment]
I compiled with the latest Pytorch ! the code is master  without modifications!

**Comment by rafaelvalle** [comment]
@raulpuric any thoughts on this error?

**Comment by raulpuric** [comment]
That's strange behavior. 
Can you print(model.state_dict()['keys']).
Is there any chance you are running BatchNorm with track_running_stats=False?

**Comment by maozhiqiang** [comment]
..../tacotron2/layers.py:35: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  self.conv.weight, gain=torch.nn.init.calculate_gain(w_init_gain))
.../tacotron2/layers.py:15: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  gain=torch.nn.init.calculate_gain(w_init_gain))
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-e7ec205f463c> in <module>()
      5 except:
      6     pass
----> 7 print(model.state_dict()['keys'])
      8 model.load_state_dict({k.replace('module.',''):v for k,v in torch.load(checkpoint_path)['state_dict'].items()})
      9 _ = model.eval()

KeyError: 'keys'

**Comment by raulpuric** [comment]
sorry I meant model.state_dict().keys()

**Comment by freds0** [comment]
I'm facing the same problem. What was the solution?
