### ISSUE TITLE
Is complete retraining necessary when adding additional source audio?

### ISSUE THREAD

**Issue by youmebangbang** [NVIDIA/tacotron2#350]
If I have a model already trained on 10hrs of source and add another 5 hours would it be better to resume training at the last checkpoint or restart the training process from beginning?

**Comment by EuphoriaCelestial** [comment]
I think you can just add more data and continue training, it may cause train loss and validate loss increase at first, but it will get better by the time

**Comment by youmebangbang** [comment]
k ill have to experiment, thx
