### ISSUE TITLE
Silence after inference 

### ISSUE THREAD

**Issue by OOps717** [NVIDIA/tacotron2#352]
Hello, I have an issue after proceeding inference. After training every time when I try to use model from different checkpoints it gives the silent result.

Below you can see my spectrograms:
![inf](https://user-images.githubusercontent.com/49514877/82424419-3436cd00-9a96-11ea-8cbf-8ad6bd30e97f.jpg)

Does anyone have suggestions how to solve it?

**Comment by ksaidin** [comment]
You don't have your attention plot is not aligned yet.

Even without alignment, you should be hearing some kind of incomprehensible noise.

**Comment by OOps717** [comment]
I expected to hear something, but even with different checkpoints I don't hear anything

**Comment by ksaidin** [comment]
Nothing to do with different checkpoints, it will produce some random voice anyway even in 1000 iterations.

You need to double check your settings, packages, models etc. or even try resetting your kernel.

**Comment by ksaidin** [comment]
btw, if you are using google colab, sometimes waveglow.infer may return array full of nans.

solution; factory reset runtime.

**Comment by OOps717** [comment]
I have tried it but still no progress. However I noticed this warning 
```
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'glow.Invertible1x1Conv' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
```
Maybe this is the problem, but I don't know how to solve it anyway :(

**Comment by ksaidin** [comment]
[>> © You can ignore those warnings.](https://github.com/NVIDIA/tacotron2/issues/226#issuecomment-506969808)

If you are using google colab, you can share ipynb so we can look at it.

**Comment by OOps717** [comment]
https://drive.google.com/file/d/12qSWw3DZcbxG5QVy1VTlAoINuFyRVRRe/view?usp=sharing

Also I am installing another version of numpy since every time after restarting runtime with numpy 1.13.3 my colab crushes.

**Comment by ksaidin** [comment]
remove all installations, (requirements.txt, numpy) google colab has almost everything preinstalled and works fine. just leave !pip install Unidecode and choose tensorflow version.

%tensorflow_version 1.x
from google.colab import drive
drive.mount('/content/drive')
%cd 'drive/My Drive/nvidia_tacotron2'
!pip install Unidecode

rest is Tacotron 2 inference code.

**Comment by OOps717** [comment]
I have run with changes according to your suggestions however it still returns silence. However, I noticed that while synthesizing audio it also returns warning:
```
/usr/local/lib/python3.6/dist-packages/IPython/lib/display.py:135: RuntimeWarning: invalid value encountered in true_divide
  scaled = np.int16(data/np.max(np.abs(data))*32767).tolist()
```

I think there is a problem with wave glow, as the mel spectrogram seems to be more or less okay, but I am not sure.

**Comment by ksaidin** [comment]
yes, you have mel_outputs_postnet which is not empty but waveglow.infer is returning empty array. (that last warning is about divide by NaN)

I've seen this problem before and it was solved by factory reset runtime and colab started to load waveglow properly.

**Comment by OOps717** [comment]
Yeap, I have done it. Have you run inference on colab ? I suppose maybe there is a problem with pretrained wave glow model or implementation of it in this notebook

**Comment by ksaidin** [comment]
You can try [this model of waveglow](https://github.com/NVIDIA/tacotron2/issues/333#issuecomment-613786357). I've tested google colab with this one.

No, I didn't run your inference, it'd ask for oauth code. Btw, you don't have a matplotlib problem, you can basically remove plot_data for now if it is worrying you.

**Comment by OOps717** [comment]
I finally solved it by replacing :
```
waveglow_path = 'waveglow_256.pt'
waveglow = torch.load(waveglow_path)['model']
```
to
```
waveglow = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_waveglow')
```

**Comment by 41WhiteElephants** [comment]
> I finally solved it by replacing :
> 
> ```
> waveglow_path = 'waveglow_256.pt'
> waveglow = torch.load(waveglow_path)['model']
> ```
> 
> to
> 
> ```
> waveglow = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_waveglow')
> ```

I used this tip to solve my issue for a long time but unfortunately it stopped working:
`Downloading: "https://github.com/nvidia/DeepLearningExamples/archive/torchhub.zip" to /home/ec2-user/.cache/torch/hub/torchhub.zip
Traceback (most recent call last):
  File "predictor.py", line 89, in inference
    audio = predict(sequence)
  File "predictor.py", line 43, in predict
    waveglow = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_waveglow')
  File "/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/custom_pytorch_p36/lib/python3.6/site-packages/torch/hub.py", line 369, in load
    model = entry(*args, **kwargs)
  File "/home/ec2-user/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub/hubconf.py", line 189, in nvidia_waveglow
    from PyTorch.SpeechSynthesis.Tacotron2.models import batchnorm_to_float
  File "/home/ec2-user/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub/PyTorch/SpeechSynthesis/Tacotron2/models.py",line 33, in <module>
    from waveglow.model import WaveGlow
ModuleNotFoundError: No module named 'waveglow.model'`
