### ISSUE TITLE
Training Tacotron2 Model for a Different Sample Rate: Parameters to be modified

### ISSUE THREAD

**Issue by fatihkiralioglu** [NVIDIA/tacotron2#359]
Hi,
Do we need to modify parameters other than sampling_rate and mel_fmax in hparams.py in order to train a model in 8kHz ?

sampling_rate=22050, #should be 8000
filter_length=1024, 
hop_length=256,
win_length=1024,
 n_mel_channels=80,
mel_fmin=0.0,
mel_fmax=8000.0, #should be decreased to 4000 at least

I suspect that  win_length  and hop_length may need to be modified if it related to windowing in waveform domain.

Thanks.

**Comment by ksaidin** [comment]
Yes, filter length, hop length and win length are calculated through sample rate. Also filter_length should be bigger than or equal to win_length.

I am not sure about mel_fmax, we don't have any assertion while building mel basis like [rayhane-mamah's](https://github.com/Rayhane-mamah/Tacotron-2/blob/ab5cb08a931fc842d3892ebeb27c8b8734ddd4b8/datasets/audio.py#L244). I am trying to understand how to tune mel_fmax correctly for male voice.

**Comment by EuphoriaCelestial** [comment]
I wonder if lower sampling rate in training data will affect training/inference speed? maybe it will be faster?

**Comment by fatihkiralioglu** [comment]
When I lowered sample rate by half and hept the win_length at 1024, the trainnig speed increased two fold. However, this approach may not be correct. For example, if we want to train our models in 8000Hz instead of 22050Hz, the folloing parameters should be used as fas as I understand:

sampling_rate= 8000
filter_length=1024,  3related to fft , it is contant
hop_length=256, # constant, related to filter_length
win_length=400, #should be proportional to sampling rate
n_mel_channels=80,
mel_fmin=0.0,
mel_fmax=4000.0, #should be decreased to the half of sampling rate

**Comment by ksaidin** [comment]
@fatihkiralioglu that will make >30ms frame hop

**Comment by fatihkiralioglu** [comment]
@ksaidin Then, if I make thow lfollowing configuration, do i get a hop length of 12.5 ms?

sampling_rate= 8000
filter_length=400, #related to fft , it is constant
hop_length=100, # constant, proportional to filter_length
win_length=400, #should be proportional to sampling rate, it corresponds to about 50ms
n_mel_channels=80,
mel_fmin=0.0,
mel_fmax=4000.0, #should be decreased to the half of sampling rate

**Comment by ksaidin** [comment]
I think so. 

As for mel_fmax, as I said, I am not sure. Official tacotron 2 paper says:

> We transform the STFT magnitude to the mel scale using an 80
> channel mel filterbank spanning 125 Hz to 7.6 kHz, followed by log
> dynamic range compression. Prior to log compression, the filterbank
> output magnitudes are clipped to a minimum value of 0.01 in order
> to limit dynamic range in the logarithmic domain

and @Rayhane-mamah says:
>> ... [even if I still don't understand the actual reason behind it](https://github.com/Rayhane-mamah/Tacotron-2/issues/6#issuecomment-370940235). 

Any tacotron expert around?

**Comment by CookiePPP** [comment]
@ksaidin 
I'm a tacotron novice, but I can confirm that WaveGlow will try and recreate features not seen in the input.
I trained a WaveGlow model with f_min of 1000Hz to 30K iters a while ago and it was able to predict the missing frequency range to a reasonable quality.

---

Found it, clearly still very early in training, but you can see that it's able to predict the f0 despite not being given it.

![paste](https://user-images.githubusercontent.com/42448678/83286850-8daaa480-a1d8-11ea-9bc7-51ca9bd394e5.png)

**Comment by ksaidin** [comment]
Even if I understand what we are doing, sometimes it seems magic.

**Comment by fatihkiralioglu** [comment]
Hi, 
I have used the folloowing parameters for 8kHz training and results are pretty good:
```
max_wav_value=32768.0,
sampling_rate=8000,
filter_length=1024,
hop_length=256,
 win_length=1024,
n_mel_channels=80,
mel_fmin=0.0,
mel_fmax=4000.0,
```

Interestingly, I only changed sampling rate and related mel_fmax and I did not modified win_length and hop_length and results are satisfactory. I have applied the same parameter change for waveglow traiining for 8kHz model, It seems that, updating only sampling_rate and mel_fmax is enough for both projects.

**Comment by evelynyhc** [comment]
> 嗨，
> 我在8kHz训练中使用了以下参数，效果非常好：
> 
> ```
> max_wav_value=32768.0,
> sampling_rate=8000,
> filter_length=1024,
> hop_length=256,
>  win_length=1024,
> n_mel_channels=80,
> mel_fmin=0.0,
> mel_fmax=4000.0,
> ```
> 
> 有趣的是，我只更改了采样率和相关的mel_fmax，而没有修改win_length和hop_length，结果令人满意。我对8kHz模型的波光训练应用了相同的参数更改，看来对于两个项目，仅更新sample_rate和mel_fmax就足够了。

hello, i want to train the model with sampling rate=16000, is there any other parameter should be changed except sr?
