### ISSUE TITLE
Question about training from scratch

### ISSUE THREAD

**Issue by harry6two** [NVIDIA/tacotron2#360]
Should training from scratch provide a checkpoint(.pt) file? If so is there a guide someone can point me to that explains how to do this? Using the following command would lead me to believe the file would be saved in the folder "outdir" but this is not the case. The training runs through each epoch without any errors and ends.

`python train.py --output_directory=outdir --log_directory=logdir`

**Comment by ksaidin** [comment]
Quick reply before spacex hatch open; training from scratch presumes you won't use pretrained model. Though you may want to use [pretrained waveglow model](https://drive.google.com/open?id=1rpK8CzAAirq9sWZhe9nlfvxMF1dRgFbF) or you can train it from scratch as well.

**Comment by harry6two** [comment]
> Quick reply before spacex hatch open; training from scratch presumes you won't use pretrained model. Though you may want to use [pretrained waveglow model](https://drive.google.com/open?id=1rpK8CzAAirq9sWZhe9nlfvxMF1dRgFbF) or you can train it from scratch as well.

Thanks for the response. I believe I'm missing something simple as I'm not sure how the checkpoint file is generated. I've tried creating the checkpoint from scratch and it does not output anything to the outdir folder other than the logdir folder and log files. I tried training using the pre-existing model and after 500 epochs it sounds exactly like the default model voice before I trained it. The repository instructions are vague and offer little information on training other than the commands. Is there a .pdf or a tutorial that goes through the steps of creating the checkpoint file through training and then loading it for use?

Thanks again for helping.

**Comment by ksaidin** [comment]
You mean you can't find a checkpoint_xxxx file under outdir folder after xxxx iterations?

xxxx is equal to what you have as iters_per_checkpoint in your hparams file.

**Comment by ksaidin** [comment]
@harry6two and it is generated when you warm start?

**Comment by harry6two** [comment]
> @harry6two, You mean you can't find a checkpoint_xxxx file under outdir folder after xxxx iterations? But it is generated when you warm start?
> 
> (xxxx is equal to what you have as `iters_per_checkpoint` in your hparams file.)

This is correct. I double checked and it does not generate any checkpoints when running the warm start either. I was mistaken in thinking that it would overwrite 'tacotron2_statedict.pt' when using it as the pre-existing model. Forgive my ignorance of tacotron 2 but this is starting to sound like something may not be enabled in 'hparams.py' or something similar. To clarify the 'outdir/logdir' is populating with log files so I don't think it is any kind of folder access issue with windows 10. In 'hparams.py' iters_per_checkpoint=1000. I tried changing it to 10 but it did not make any difference.

Thanks again for the help.

**Comment by ksaidin** [comment]
@harry6two That's strange. It should be generating checkpoint_0 file anyway before starting.

Have you tried to debug [this line](https://github.com/NVIDIA/tacotron2/blob/fc0cf6a89a47166350b65daa1beaa06979e4cddf/train.py#L117)?

**Comment by harry6two** [comment]
> @harry6two That's strange. It should be generating checkpoint_0 file anyway before starting.
> 
> Have you tried to debug [this line](https://github.com/NVIDIA/tacotron2/blob/fc0cf6a89a47166350b65daa1beaa06979e4cddf/train.py#L117)?

The line does not break. I set breaks on the function that calls `save_checkpoint()` and eventually found that the second for loop in the main training loop seems to be the last place it breaks, never calling `save_checkpoint().` [This line](https://github.com/NVIDIA/tacotron2/blob/fc0cf6a89a47166350b65daa1beaa06979e4cddf/train.py#L209) in the for loop is the only part that executes, everything inside of it does not execute.

**Comment by ksaidin** [comment]
@harry6two , I think you have an empty train_loader or something. 

I am training on windows10 too, inside conda environments. 

Can you please ensure [prepare_dataloaders function](https://github.com/NVIDIA/tacotron2/blob/fc0cf6a89a47166350b65daa1beaa06979e4cddf/train.py#L65) is not returning empty train loader?

**Comment by harry6two** [comment]
> @harry6two , I think you have an empty train_loader or something.
> 
> I am training on windows10 too, inside conda environments.
> 
> Can you please ensure [prepare_dataloaders function](https://github.com/NVIDIA/tacotron2/blob/fc0cf6a89a47166350b65daa1beaa06979e4cddf/train.py#L65) is not returning empty train loader?

Not sure if I did this right but it gives me the following when checking the value of `train_loader` before it's returned:

`<torch.utils.data.dataloader.DataLoader object at 0x0000016E89206F28>`

**Comment by ksaidin** [comment]
That might be an empty object, check with `print(len(train_loader ))`

**Comment by harry6two** [comment]
> That might be an empty object, check with `print(len(train_loader ))`

It returns a length of 0.

**Comment by ksaidin** [comment]
OK, let's start from the beginning. What kind of dataset you are training? 

Btw, [these steps](https://github.com/NVIDIA/tacotron2/issues/321#issuecomment-603894212) are very userful to start with.

**Comment by harry6two** [comment]
> OK, let's start from the beginning. What kind of dataset you are training?
> 
> Btw, [these steps](https://github.com/NVIDIA/tacotron2/issues/321#issuecomment-603894212) are very userful to start with.

I made two .wav(44.1k @ 16bit) files that are ~10 words each. I remade the files again(tried mono and stereo) and created new training and validation lists but the results are the same. I did notice that I can change the file path to the .wavs in each file and it does not give me any kind of error message when training. To me it sounds like I have the file paths wrong or it is not attempting to load any of the .wavs.

In `hparams.py` I have:
```
training_files='filelists/train.txt',
validation_files='filelists/val.txt',
```

train.txt contents:
```
wav/r1.wav|A room without books is like a body without a soul.
wav/r2.wav|The night is darkest just before the dawn.
```
val.txt contents:
```
wav/r1.wav|A room without books is like a body without a soul.
```

File structure:
```
tacotron2 (main folder)
- filelists
-- (train.txt & val.txt)
- outdir
-- logdir
- wav
-- (r1.wav & r2.wav)
```

**Comment by ksaidin** [comment]
No, it doesn't work that way. You will need more than thousand audio files to train. (Total duration of 10 hours for the best result)
For ex: [LJ Speech Dataset](https://keithito.com/LJ-Speech-Dataset/) or [The World English Bible](https://www.kaggle.com/bryanpark/the-world-english-bible-speech-dataset).

**Comment by onyedikilo** [comment]
> > OK, let's start from the beginning. What kind of dataset you are training?
> > Btw, [these steps](https://github.com/NVIDIA/tacotron2/issues/321#issuecomment-603894212) are very userful to start with.
> 
> I made two .wav(44.1k @ 16bit) files that are ~10 words each. I remade the files again(tried mono and stereo) and created new training and validation lists but the results are the same. I did notice that I can change the file path to the .wavs in each file and it does not give me any kind of error message when training. To me it sounds like I have the file paths wrong or it is not attempting to load any of the .wavs.
> 
> In `hparams.py` I have:
> 
> ```
> training_files='filelists/train.txt',
> validation_files='filelists/val.txt',
> ```
> 
> train.txt contents:
> 
> ```
> wav/r1.wav|A room without books is like a body without a soul.
> wav/r2.wav|The night is darkest just before the dawn.
> ```
> 
> val.txt contents:
> 
> ```
> wav/r1.wav|A room without books is like a body without a soul.
> ```
> 
> File structure:
> 
> ```
> tacotron2 (main folder)
> - filelists
> -- (train.txt & val.txt)
> - outdir
> -- logdir
> - wav
> -- (r1.wav & r2.wav)
> ```

@harry6two in your train and val files, can you try to duplicate the lines so like there are at least 10 lines, such as:

wav/r1.wav|A room without books is like a body without a soul.
wav/r2.wav|The night is darkest just before the dawn.
wav/r1.wav|A room without books is like a body without a soul.
wav/r2.wav|The night is darkest just before the dawn.
wav/r1.wav|A room without books is like a body without a soul.
wav/r2.wav|The night is darkest just before the dawn.
wav/r1.wav|A room without books is like a body without a soul.
wav/r2.wav|The night is darkest just before the dawn.

and so on... and try again to see if creates a checkpoint.

**Comment by harry6two** [comment]
> @harry6two in your train and val files, can you try to duplicate the lines so like there are at least 10 lines, such as:
> 
> wav/r1.wav|A room without books is like a body without a soul.
> wav/r2.wav|The night is darkest just before the dawn.
> wav/r1.wav|A room without books is like a body without a soul.
> wav/r2.wav|The night is darkest just before the dawn.
> wav/r1.wav|A room without books is like a body without a soul.
> wav/r2.wav|The night is darkest just before the dawn.
> wav/r1.wav|A room without books is like a body without a soul.
> wav/r2.wav|The night is darkest just before the dawn.
> 
> and so on... and try again to see if creates a checkpoint.

I ended up using the LJ Speech Dataset as suggest by @ksaidin to verify that my setup was working. The method you suggested also worked. I did have to change the `batch_size` to 4 as to not overload my GPU which only has 8GB of memory.

Thanks again for all the help.
