### ISSUE TITLE
tacotron2_statedict.pt

### ISSUE THREAD

**Issue by 5859wang** [NVIDIA/tacotron2#365]
can  you priovide the link of tacotron2_statedict.pt file. thank you

**Comment by CookiePPP** [comment]
https://github.com/NVIDIA/tacotron2#training-using-a-pre-trained-model
You can open the link
[...our published Tacotron 2 model](https://drive.google.com/file/d/1c5ZTuT7J08wLUoVZ2KkUs_VdZuJ86ZqA/view?usp=sharing)

or from
https://ngc.nvidia.com/catalog/all?orderBy=modifiedDESC&pageNumber=0&query=tacotron2&quickFilter=&filters=

**Comment by NepaliTTS** [comment]
the drive requires access

**Comment by zywang99** [comment]
> the drive requires access

Have you found a way to download this file? tacotron2_statedict.pt

**Comment by MENG2010** [comment]
> > the drive requires access
> 
> Have you found a way to download this file? tacotron2_statedict.pt

Same problem here.

**Comment by vigashhh** [comment]
i found it here https://catalog.ngc.nvidia.com/orgs/nvidia/teams/dle/models/tacotron2__pyt_ckpt
