### ISSUE TITLE
Particular Letter case in English

### ISSUE THREAD

**Issue by srijan14** [NVIDIA/tacotron2#369]
I am trying to train on my custom english dataset. But the dataset size is not very huge. And for some reason, its very sensitive to the starting lettercase of the word in some contexts. Many of my what i should say unexpected output am able to fix by tweaking the first letter case of words in context.

So, was just curious to know about the impact on results if someone confines the training dataset if one only use  say for example lower case only.
Also, any other suggestion would be much appreciated.

Thanks

**Comment by CookiePPP** [comment]
https://github.com/NVIDIA/tacotron2/blob/master/hparams.py#L30
```
        text_cleaners=['english_cleaners'],
```

https://github.com/NVIDIA/tacotron2/blob/master/text/cleaners.py#L86

**Training**

```
def english_cleaners(text):
  '''Pipeline for English text, including number and abbreviation expansion.'''
  text = convert_to_ascii(text)
  text = lowercase(text)
  text = expand_numbers(text)
  text = expand_abbreviations(text)
  text = collapse_whitespace(text)
  return text
```

---

**Inference**
![paste](https://user-images.githubusercontent.com/42448678/83928722-9d059100-a788-11ea-9b44-3610dc62fa7a.png)

---

Everything in training and inference is converted to lowercase by default.

**Comment by ksaidin** [comment]
@CookiePPP btw why do we have capital letters in valid symbols?

**Comment by CookiePPP** [comment]
@ksaidin 
No idea

**Comment by srijan14** [comment]
@CookiePPP  this helps, should have checked. Presence of both case in the symbols and the effect of case in particular on my results got me confused. Not sure but  guess should be interesting to see the effect of case on the results, will try. 
Anyway closing the issue, guess the effect because of letter case in my results might have to do with something else, not sure what.
