### ISSUE TITLE
setup failed

### ISSUE THREAD

**Issue by marshonhuckleberry** [NVIDIA/tacotron2#377]
windows 10 64
python 3.6.8

setup fails, python version not specified however i found it by myself, following the steps and requirements.txt, the requirements seem to be wrong because specified tensorflow is not compatible with specified numpy, maybe because the code is for linux not windows, on windows install modules by luck. i'm very pesimistic about github comments nobody gonna ever help with that i think i finally gonna fix my issue by myself

**Comment by rafaelvalle** [comment]
What error do you get?

**Comment by marshonhuckleberry** [comment]
try yourself man, you see the errors yourself
