### ISSUE TITLE
Using Parallel WaveGan as vocoder

### ISSUE THREAD

**Issue by Charlottecuc** [NVIDIA/tacotron2#379]
Hi. I trained the tacotron2 model and can successfully synthesize voice by using WaveGlow as vocoder. However, when I turned to the Parallel WaveGan (https://github.com/kan-bayashi/ParallelWaveGAN) , the synthzised waveform is quite strange:
![Screenshot 2020-06-22 at 2 31 07 PM](https://user-images.githubusercontent.com/43811904/85255557-1691c480-b495-11ea-8812-41a31f0ddb2b.png).
![Screenshot 2020-06-22 at 2 47 42 PM](https://user-images.githubusercontent.com/43811904/85256840-6a9da880-b497-11ea-88ba-cda07bfcd071.png)
(In the training time, the hop_size, sample_rate and window_size were set as the same for the tacotron, WaveGlow and waveGan model.)

Previously, I successfully used WaveGan as vocoder to synthesize speech from the FastSpeech acoustic model. The only difference here is that in FastSpeech, mel-spectrogram features were normalized to have zero mean and unit variance before training.

My question is, in your tacotron2 implementation, except `audio_norm = audio / self.max_wav_value` , is there any other preprocessing of the input mel-spectrogram features? Or, could you kindly give me some advice?

Thank you very much!

**Comment by rafaelvalle** [comment]
Take a look at [this](https://github.com/NVIDIA/tacotron2/blob/master/data_utils.py#L37) and [this](https://github.com/NVIDIA/tacotron2/blob/185cd24e046cc1304b4f8e564734d2498c6e2e6f/layers.py#L79)

**Comment by Charlottecuc** [comment]
Thank you. For anyone who tried `tacotron2+WaveGan` and also encountered this problem, see https://github.com/kan-bayashi/ParallelWaveGAN/issues/169
