### ISSUE TITLE
Hangs when operating in multi-gpu mode.

### ISSUE THREAD

**Issue by minimumnz** [NVIDIA/tacotron2#38]
I got this to train with a single GTX 1080TI but when trying to run it on machine with 4 * GTX 1080TI

it never returns from:

torch.distributed.init_process_group(
        backend=hparams.dist_backend, init_method=hparams.dist_url,
        world_size=n_gpus, rank=rank, group_name=group_name)

I've tried a few different parameters for backend (nccl, tcp, gloo). I installed nccl from nvidia.

These are the parameters in the function:

init method: file://distributed.dpt
backend: nccl
rank: 0
group: group_2018_06_12-204429
n_gpus: 4

Is it correct to use distributed_run=True even if the gpus are in the same machine?

I'm using Cuda 8.0, Ubuntu 16.04.

**Comment by rafaelvalle** [comment]
Please check if there is a `distributed.dpt` file inside the folder where your running the model.
If there is such a file, please erase it, start training again, wait until `distributed.dpt` is created and observe it's contents. 
it should have something of the sort but not exactly:
```
group_name 1 127.0.0.1
group_name 3 127.0.0.1
group_name 4 127.0.0.1
group_name 2 127.0.0.1




```

**Comment by minimumnz** [comment]
Thanks I got passed this error with this.

**Comment by MlWoo** [comment]
@minimumnz I met the same problem, too. I also want to run the model on 2 GPUs in one node. Below is the commandline which I ran.
```bash
CUDA_VISIBLE_DEVICES=2,3 python train.py --n_gpus=2 --rank=0 --output_directory=outdir --log_directory=logdir --hparams=distributed_run=True,fp16_run=True
```
But the content of dpt file generated is below:
```
group_name# 0 43683 5 10.128.2.14 172.17.0.1 10.128.1.14 fe80::ae1f:6bff:fe27:b358 fe80::526b:4bff:fe2f:21c8
```
 and @rafaelvalle, would you like to give any suggestions to me ? Thanks in advance.

**Comment by rafaelvalle** [comment]
Great. Closing the issue.
