### ISSUE TITLE
cannot speed up when using distributed_run

### ISSUE THREAD

**Issue by zhangming8** [NVIDIA/tacotron2#392]
Hi, I find that using mult-gpu training can't speed up.
When I am using:
 "CUDA_VISIBLE_DEVICES=1,2,3 python -m multiproc train.py --output_directory=output --log_directory=logs --checkpoint_path output/checkpoint_13000 --warm_start --hparams=distributed_run=True"

the training speed is the same as:
"CUDA_VISIBLE_DEVICES=3 python train.py --output_directory output --log_directory=logs --checkpoint_path output/checkpoint_2000 --warm_start"

Is that right ???

Train loss 2550 0.397638 Grad Norm 0.882030 5.17s/it
Train loss 2551 0.373633 Grad Norm 0.627727 4.56s/it
Train loss 2552 0.406860 Grad Norm 0.576586 5.01s/it
Train loss 2553 0.409785 Grad Norm 0.325992 4.83s/it
Train loss 2554 0.401457 Grad Norm 0.336754 4.95s/it
Train loss 2555 0.395595 Grad Norm 0.366576 5.40s/it
Train loss 2556 0.399109 Grad Norm 0.291875 4.69s/it
Train loss 2557 0.385006 Grad Norm 0.354266 4.79s/it
Train loss 2558 0.387333 Grad Norm 0.317803 4.74s/it
Train loss 2559 0.401623 Grad Norm 0.400726 4.47s/it
Train loss 2560 0.406277 Grad Norm 0.466030 4.75s/it
Train loss 2561 0.396504 Grad Norm 0.528755 4.76s/it

**Comment by EuphoriaCelestial** [comment]
I tried multi gpus training once before, the biggest pros is increased batch_size
I think it is counted as "speed up"

**Comment by zhangming8** [comment]
> I tried multi gpus training once before, the biggest pros is increased batch_size
> I think it is counted as "speed up"

Yeah, I get it, thanks.
