### ISSUE TITLE
The synthetic voice has fast playback speed

### ISSUE THREAD

**Issue by wangzhenhan93** [NVIDIA/tacotron2#398]
hello，i use 18 hours of Vietnamese pronunciation training for 40 epoch，the synthetic voice has fast playback speed，is there training epoch is not s
[sound.zip](https://github.com/NVIDIA/tacotron2/files/5028268/sound.zip)
ufficient

**Comment by wangzhenhan93** [comment]
solved

**Comment by kannadaraj** [comment]
Hi @wangzhenhan93 
Please can you share how you solved it? Thanks.

**Comment by xDuck** [comment]
@wangzhenhan93 Can you let us know how you fixed this?

**Comment by hungcn** [comment]
> @wangzhenhan93 Can you let us know how you fixed this?

Hey, I had the same problem, it might be because the hifi-gan pretrained model was trained on sampling rate=22k and your mel was computed with config at 16k sampling rate. I fixed it by re-train Hifi-gan on 16k dataset

**Comment by WhiteFu** [comment]
@wangzhenhan93 Can you let us know how you fixed this?
