### ISSUE TITLE
Checkpoint error "AssertionError"

### ISSUE THREAD

**Issue by flightofthenavigator** [NVIDIA/tacotron2#402]
Hello,
I come here to ask for help. Whenever i put --checkpoint_path at the end of python train.py --output_directory=outdir --log_directory=logdir -c tacotron2_statedict.pt --warm_start, this happens:
`
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 194, in train
    checkpoint_path, model, hparams.ignore_layers)
  File "train.py", line 85, in warm_start_model
    assert os.path.isfile(checkpoint_path)
AssertionError
`
Can someone help please? Thanks!

**Comment by flightofthenavigator** [comment]
nvm lol

**Comment by ronaldaug** [comment]
I got the same error like your, is your issue fixed?
