### ISSUE TITLE
Deal with abnormal sentences.

### ISSUE THREAD

**Issue by Thien223** [NVIDIA/tacotron2#410]
My tacotron model cannot synthesize the abnormal sentences well. 
I have found that a lot of TTS service can deal with this problem. But I don't know how did they do.

Is the training data included abnormal sentences,
or they used any technique to overcome this issue, or just another TTS model could do this itself.

Anyone has idea? Thank you so much.

**Comment by youmebangbang** [comment]
Add to your training set fragments of your sentences, as long as they are at least 1 sec long.
