### ISSUE TITLE
Training parameters for deeper/bass male voice

### ISSUE THREAD

**Issue by kannadaraj** [NVIDIA/tacotron2#411]
I am having trouble to train and synthesize deep male voice. I have good quantity of the speakers data (~20 hours). I have been unsuccessful in training to the male voice. The loss keeps decreasing, but alignment never happens. All precautions are taken to ensure that the data is formatted and silence is removed at ends. The synthesis quality never improves even after training for more than 300K iterations. 

Please can anyone suggest do i need to change any specific settings/modifications needed to synthesize such data. Thanks.

**Comment by youmebangbang** [comment]
It shouldn't be a problem training a male voice, even warm starting from LJSpeech model. Alignment can be tricky sometimes. If you don't see it by 10k iterations then things went wrong and you need to retry from starting checkpoint. Setting the attention dropout temporarily to .4 can help, then reduce to .1 after alignment shows. You may need to retry several times. Also to trimming silence, readd .5 seconds of silence to end of each wav.  Make sure your text has a end of line character as well such as a '~'.

**Comment by kannadaraj** [comment]
@youmebangbang thanks a lot for the suggestions. I will try this out.

**Comment by kannadaraj** [comment]
@youmebangbang this helped a lot.. Thanks for your suggestion.
