### ISSUE TITLE
Any plan to release code: tacotron2 with GMM attention ?

### ISSUE THREAD

**Issue by xiaoyangnihao** [NVIDIA/tacotron2#425]

**Comment by prattcmp** [comment]
GMMA and DCA are similar in quality. Not exactly sure why you want GMMA, but here's a DCA implementation: https://github.com/bshall/Tacotron

**Comment by xiaoyangnihao** [comment]
thanks

**Comment by LeoniusChen** [comment]
> thanks

Now you can use codes in this [Repo](https://github.com/LeoniusChen/Attentions-in-Tacotron) to implement DCA or GMM attention.

**Comment by xiaoyangnihao** [comment]
@prattcmp @LeoniusChen, thanks, I will try.
