### ISSUE TITLE
How to generate mel with teacher forcing for further use like hifi-gan?

### ISSUE THREAD

**Issue by blx0102** [NVIDIA/tacotron2#431]
Should I just go through the training/validation procedures and write out the y_pred?

**Comment by youssefavx** [comment]
@blx0102 Did you manage to figure this out? Hifi Gan unfortunately didn't provide any further instructions, so I'm also confused as to how to generate those from wav files. The examples provided on the inference section of the read me only do so for text it seems.

**Comment by spolezhaev** [comment]
I wrote a script for extracting mels and alignments with teacher forcing. You can find it [here](https://gist.github.com/Piteryo/79056e362095e72f4a4341066171e304)

**Comment by blx0102** [comment]
> I wrote a script for extracting mels and alignments with teacher forcing. You can find it [here](https://gist.github.com/Piteryo/79056e362095e72f4a4341066171e304)

That's really nice! thanks mate!

**Comment by debasish-mihup** [comment]
> I wrote a script for extracting mels and alignments with teacher forcing. You can find it [here](https://gist.github.com/Piteryo/79056e362095e72f4a4341066171e304)

The script is incomplete uses few imports which is not present in this repo

```
    guide_attention_fast
```
