### ISSUE TITLE
are there any specs for sampling of audio recording?

### ISSUE THREAD

**Issue by yerzhan7orazayev** [NVIDIA/tacotron2#441]
Is there any requirements for sampling rate of audio files? 

Since, the original dataset is recorded at a sampling rate of 22050 Hz. Should one convert own dataset to this sampling rate?

Thanks.

**Comment by CookiePPP** [comment]
Yes, you should use 22050Hz sampling rate audio files unless you have experience changing [these parameters](https://github.com/NVIDIA/tacotron2/blob/master/hparams.py#L36-L39).

I definitely recommend resampling your audio to 22050Hz as that is the standard for most pretrained models.

**Comment by yerzhan7orazayev** [comment]
Thanks,

Also, the input to the model is normalized text or the original text? 
By normalized I mean the transcription with numbers, ordinals, and monetary units expanded into full words. 
If this is the case, during inference there should be one more algorithm that does this normalization procedure, please correct me if I am wrong.

**Comment by CookiePPP** [comment]
https://github.com/NVIDIA/tacotron2/blob/master/text/cleaners.py#L88

There is a system for expanding numbers and abbreviations but I don't think it contains enough examples to use on everyday text, so I'd suggest using normalized text as much as possible.

**Comment by yerzhan7orazayev** [comment]
Thanks. @CookiePPP
