### ISSUE TITLE
Which is worse: too long utterances or too short utterances?

### ISSUE THREAD

**Issue by sajattack** [NVIDIA/tacotron2#447]
I'm using automated subtitling with the Google Speech to Text API to prepare a dataset. By default, the sections it breaks subtitles down into are approximately 2 seconds long on average. I've found a tool to assemble the subtitle sections on sentence boundaries and it gives longer sections, but my speaker isn't scripted and so he sometimes corrects his train of thought midsentence and now I have some sentences upwards of 20 seconds long. So I'm wondering which is the better option. I think it might be better to eliminate problematic (too long) sentences and go with the 2nd option, but I'd like to hear from someone who has more expertise in this area.

**Comment by johnjaniczek** [comment]
If you train with 2 second phrases I think you will run into problems generating longer phrases. I've noticed the model will "rush" through phrases that are significantly longer than what it has been trained on.

The long phrases might cause memory issues and force you to use a small batch size - unless you have bountiful GPU memory :) Or the other option is to eliminate the longer phrases as you suggested. 

There are pro's and con's to each method. I agree with you the second option will probably work the best and simplest. Another thought is that after training on the "medium" length phrases you can fine-tune the model on the long/short phrases with a small batch size to learn how a variety of phrase lengths should be handled. I've noticed that you need a variety of phrase lengths in the training pool to be robust at inference time, it appears to be challenging to generalize outside the phrase lengths in the training pool.
