### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.93 GiB total capacity; 11.07 GiB already allocated; 19.75 MiB free; 11.36 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by jinny1208** [NVIDIA/tacotron2#450]
Hello, I am a beginner so any help would be appreciated. 

I am currently connected to a GPU server using a virtual environment with anaconda. I have installed all the required dependencies listed in the requirements.txt file, except for tensorflow, which I am using version 1.15. Additionally, I have installed pytorch using the following command: conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch

I have not modified any code-only the path to the wav files of the LJSpeech dataset in the filelists directory. 

When I run the code using "python train.py --output_directory=outdir --log_directory=logdir" the error message below occurs.
**RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.93 GiB total capacity; 11.07 GiB already allocated; 19.75 MiB free; 11.36 GiB reserved in total by PyTorch)
**

Is there any way to solve this? Thanks in advance.

**Comment by jinny1208** [comment]
As a random guess, I changed the batch_size in hparams.py from 64 to 32 and now it seems to be okay. Can anyone explain why batch_size solves the problem?

**Comment by sajattack** [comment]
I'm pretty new to the topic myself, but as far as I understand it, batch size controls how many "batches" are training at once, and more batches takes more memory to train.
