### ISSUE TITLE
module compiled against API version 0xc but this version of numpy is 0xb

### ISSUE THREAD

**Issue by syoyo** [NVIDIA/tacotron2#5]
OS: Ubuntu 16.04
CUDA: 9.0
Python: 3.6(Conda)

When I try to run `train.py`, I got an error message as in the issue title.

It looks tensorflow 1.5.0 + numpy 1.13.3 + python 3.6 combination is somewhat problematic.

https://github.com/tensorflow/tensorflow/issues/16488
https://github.com/eldar/pose-tensorflow/issues/68

At least I have confirmed updating `tensorflow` to 1.6.0 in `requirements.txt` solved the issue.

**Comment by rafaelvalle** [comment]
Can you pull and confirm that the unspecified tensorflow requirements work?

**Comment by raulpuric** [comment]
same error as other issue.
See https://github.com/NVIDIA/tacotron2/tree/padding-patch-0.4 should work now. 
will merge in an hour or so when others are convince as well :)

**Comment by rafaelvalle** [comment]
@syoyo please pull from master and confirm that it works for you.

**Comment by syoyo** [comment]
Thank! Confirmed now its fixed.
