### ISSUE TITLE
Is it a good idea to continue training from where I left off after updating my dataset?

### ISSUE THREAD

**Issue by Aayzie** [NVIDIA/tacotron2#518]
Let's say I'm at 50 epoch, and then I updated my dataset by adding new lines, is it better to continue from my last checkpoint before I updated the dataset, or is it better to start over from the pretrained LJ model?
Thanks :)

**Comment by creator-kevinovich** [comment]
It depends on the specific algorithm/framework you are using to train your model. Some of them support incremental learning. If this is the case, you can add data to your model afterwards to update your model weights.

**Comment by Aayzie** [comment]
> It depends on the specific algorithm/framework you are using to train your model. Some of them support incremental learning. If this is the case, you can add data to your model afterwards to update your model weights.

Okay Pog thanks
