### ISSUE TITLE
Create Mel Spectrograms

### ISSUE THREAD

**Issue by jafwefjauwhf** [NVIDIA/tacotron2#559]
I got an error on this step, any idea on how to fix?
![image](https://user-images.githubusercontent.com/69084337/163561683-69059b1d-3a4a-4443-b5df-ed1a5f18cc4b.png)

**Comment by jafwefjauwhf** [comment]
please someone help quickly like today, i need to do this today or else i will get covered in ice by my friends

**Comment by a897456** [comment]
what is the format of the npy files about the Mel Spectrograms?[1,1,173710]?

**Comment by jafwefjauwhf** [comment]
this issue is closed and has been for more than a year... also i dont even use tacotron2 anymore

**Comment by a897456** [comment]
Sorry to bother you. I'm a newbie, new to this field. how do you create Mel Spectrograms now? What tools replace the tacotron2?

**Comment by jafwefjauwhf** [comment]
i dont remember gonna be honest
