### ISSUE TITLE
Distributed training hangs after "Initializing distributed" message

### ISSUE THREAD

**Issue by gsoul** [NVIDIA/tacotron2#56]
Hello everyone

I try to run Tacotron2 training in distributed mode. But when I run the command - it hangs and never reaches the training phase. No errors are shown.

The command I use:
```
CUDA_VISIBLE_DEVICES=0,1 python3 -m multiproc train.py --output_directory=outdir --log_directory=logdir -c=outdir/checkpoint_86000  --hparams=batch_size=36,distributed_run=True
```
What I tried so far:
1. Switch distributed.py file to this one: https://github.com/yhgon/tacotron2/blob/master/distributed.py
2. Use apex.parallel.multiproc instead of multiproc from the repo. In this case I get this error:
```
Traceback (most recent call last):
  File "/home/soul/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/soul/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/soul/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/__init__.py", line 2, in <module>
    from . import reparameterization
  File "/home/soul/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/reparameterization/__init__.py", line 1, in <module>
    from .weight_norm import WeightNorm
  File "/home/soul/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/reparameterization/weight_norm.py", line 3, in <module>
    from ..fp16_utils import Fused_Weight_Norm
  File "/home/soul/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/fp16_utils/__init__.py", line 13, in <module>
    from .fused_weight_norm import Fused_Weight_Norm
  File "/home/soul/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/fp16_utils/fused_weight_norm.py", line 4, in <module>
    import apex_C
ImportError: /home/soul/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE
```
3. Follow advices from this issue: https://devtalk.nvidia.com/default/topic/1036195/container-pytorch/imagenet-hang-on-dgx-1-when-using-multiple-gpus-/
with no luck
4. Reboot the server

My set-up:
Ubuntu 16.04.1
PyTorch 0.4
cuda 9.0 with cudnn

Any ideas would be greatly appreciated.

P.S. As far as I can tell, the code hangs on this line of code:
`torch.distributed.init_process_group()`
from train.py, but I'm not really familiar with PyTorch to further debug it.

**Comment by yhgon** [comment]
@gsoul  sometime, you need to eliminate previous distributed.dpt file manually. 

for distributed training with FP16,  I've just replace  only distributed.py file with APEX one.  I didn't reveiwed and tested multiproc.py file in APEX.  plz use original one. 

below is reproduction step. plz use nvidia-docker. 

Step1.  pull my docker image base on NGC 18.06  which I already install requirements
``` 
docker pull hryu/pytorch:t3-1
```

which I use below Dockerfile to build 
```
FROM   nvcr.io/nvidia/pytorch:18.06-py3

RUN  pip install  cython  numpy  scipy matplotlib  librosa==0.6.0  inflect==0.2.5 Unidecode==1.0.22 tensorflow  tensorboardX jupyter
```

Step2.  launch docker 
for nvidia-docker 2.0
```
docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0,1,2,3  --shm-size=1g --ulimit memlock=-1  --name=t2-ngc-test -ti hryu/pytorch:t3-1 
``` 
or for nvidia-doker 1.0
```
export NV_GPU=0,1,2,3; nvidia-docker run    --shm-size=1g --ulimit memlock=-1 --name=t2-ngc-test -ti hryu/pytorch:t3-1 
```

Step3.  run train 
```
python -m multiproc train.py --output_directory=outdir --log_directory=logdir --hparams=distributed_run=True,fp16_run=True
```

**Comment by yhgon** [comment]
when I check  multiproc.py file from APEX, it use  `--world-size` for argument instead of ` num_gpus`  and `--n_gpus`

**Comment by gsoul** [comment]
Thanks a lot for your detailed reply!

>@gsoul sometime, you need to eliminate previous distributed.dpt file manually.
This advise solved issue for me.

**Comment by willian56** [comment]
1

**Comment by willian56** [comment]
1

**Comment by Approximetal** [comment]
> Thanks a lot for your detailed reply!
> 
> > @gsoul sometime, you need to eliminate previous distributed.dpt file manually.
> 
> This advise solved issue for me.

I didn't find  'distributed.dpt' in my folder, but it still hangs after "Initializing distributed" . Do you have any solutions? @gsoul  @rafaelvalle
