### ISSUE TITLE
Getting TypeError: pad_center() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by prajwalkolte8301** [NVIDIA/tacotron2#586]
I am getting this error  whenever i try to start the training
Please Help!!

![image](https://user-images.githubusercontent.com/64357565/221036967-3e4fcdd3-0ae3-418a-9536-237109072847.png)

**Comment by ZarrarAhmedKhan** [comment]
Same here.
@prajwalkolte8301 did you find the solution for this?

**Comment by prajwalkolte8301** [comment]
> Same here. @prajwalkolte8301 did you find the solution for this?

Yes, I downgraded the package librosa to 1.x and the code worked.

**Comment by arodriguezg98** [comment]
Wrong version was specified. I'm using version 0.9.2. Don't forget to restart your jupyter netbook kernel.
