### ISSUE TITLE
pad_center issue in sttf.py file

### ISSUE THREAD

**Issue by KarthikAitha** [NVIDIA/tacotron2#623]
Generating Mels
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-47-77c0c190c00d>](https://localhost:8080/#) in <cell line: 1>()
      1 if generate_mels:
----> 2     create_mels()

2 frames
[/content/tacotron2/stft.py](https://localhost:8080/#) in __init__(self, filter_length, hop_length, win_length, window)
     65             # get window and zero center pad it to filter_length
     66             fft_window = get_window(window, win_length, fftbins=True)
---> 67             fft_window = pad_center(fft_window, filter_length)
     68             fft_window = torch.from_numpy(fft_window).float()
     69 

TypeError: pad_center() takes 1 positional argument but 2 were given

**Comment by gupt29** [comment]
use this 

fft_window = pad_center(fft_window, size=filter_length)

**Comment by KarthikAitha** [comment]
Thank you
