### ISSUE TITLE
Silence in dataset a problem?

### ISSUE THREAD

**Issue by codemandosch** [NVIDIA/tacotron2#63]
The speaker in my dataset waits a few seconds before starting to speak in each recording. There is also a few seconds of near silence afterwards. The duration varies and it's not complete silence (it has some minor mic noise) so it's hard to remove. Will this be a problem?

**Comment by codemandosch** [comment]
Found a good way to clean it using sox
`
sox inputfile.mp3 outputfile.mp3 silence 1 0.1 0.1% reverse silence 1 0.1 0.1% reverse`

**Comment by atliSig** [comment]
I had issues with alignment when I trained on a dataset with these starting and ending silences. Additionally you can trim the silence using librosa with: ``trimmed_audio, _ = librosa.effect.trim(audio)``.

**Comment by codemandosch** [comment]
@atliSig How do I interpret the alignment graph? Any good resources to read or should I just try to read the code? This is my Graph after 150 000 iterations, audio is incomprihensible:
![image](https://user-images.githubusercontent.com/39131332/43455373-db35e84a-94bf-11e8-81a2-b54c8cfe54f6.png)
Should be mentioned that my batch_size is only 5 because of memory problems (I run a 1070 8GB but my dataset seems to be more demanding in memory than LJ). Batch size restricts how much training is done per iteration right?

I made a slack channel if you would care to join. Would be nice to exchange ideas and help eachother out:

https://join.slack.com/t/tacotron2/shared_invite/enQtNDAxNTM5ODAwNzI1LTcwZDI1ZWRhMGNlN2FhMjBkMGU3NjU4M2IwNWY3YzFmZGZkZDdhNjIxNDJmZmJjZmZhZTY2MWU0YWZjZDEwMGY

**Comment by atliSig** [comment]
Based on the number of iterations you have finished and the state of the alignment I would guess something has gone wrong in your case. The alignment graph gives you an idea about how well the attention-based decoder is aligning the input text sequence to the waveform output.

Looking at your alignment graph, it seems like the model has a hard time predicting the first 60 encoder timesteps / 500 decoder timesteps, in the sense the model does not know which parts of the input text correspond to which part of the output waveform. Finally it seems like the decoder predicts with a higher probability that the later encoder timesteps represent about 200 decoder timesteps, which could correspond to a dragged-out pronunciation in the end of your output.

You can take a look at this seq2seq alignment graph to get a better understanding for what you should be looking for in your alignment graph, which ideally is a very concentrated diagonal line representing a high confidence in the alignment of text and waveform
![alignment](http://mogren.one/graphics/illustrations/2016-08-08/bahdanau-etal-alignment.png)
