### ISSUE TITLE
multi-gpu error

### ISSUE THREAD

**Issue by willian56** [NVIDIA/tacotron2#64]
hello, everyone, I am trying to run the tacotron2 with multi-gpu, my command is
``` python -m multiproc train.py --output_directory=outdir --log_directory=logdir --hparams=distributed_run=True,fp16_run=True ```

the output as following:
``` FP16 Run: True ```
``` Dynamic Loss Scaling: True ```
``` Distributed Run: True ```
``` cuDNN Enabled: True ```
``` cuDNN Benchmark: False ```
``` Initializing distributed ```

and it hangs and never go to the training step. If there any advice for this problem? Thanks for your reply sincerely.

**Comment by gsoul** [comment]
https://github.com/NVIDIA/tacotron2/issues/56

**Comment by willian56** [comment]
@gsoul yeah, thanks for your suggestion, I have viewed #56, but I am not familiar with docker, so I wonder if there is another solution for this problem.

**Comment by gsoul** [comment]
do you have "distributed.dpt" file in the root of the repo folder and did you try to manually delete it?

**Comment by willian56** [comment]
yeah, the "distribted.dpt" is in my repo folder, Does it work to delete it?

**Comment by rafaelvalle** [comment]
Yes. Delete the file and please confirm that it works.

**Comment by willian56** [comment]
@rafaelvalle @gsoul yeah, thanks for your advice. But there still a problem, finally I replace distributed.py with APEX distributed.py filehttps://raw.githubusercontent.com/NVIDIA/apex/master/apex/parallel/distributed.py

**Comment by begeekmyfriend** [comment]
It also works for me. @rafaelvalle why not replace `distributed.py` with this one on your repo?

**Comment by yizhidamiaomiao** [comment]
> @rafaelvalle @gsoul yeah, thanks for your advice. But there still a problem, finally I replace distributed.py with APEX [distributed.py](https://raw.githubusercontent.com/NVIDIA/apex/master/apex/parallel/distributed.py) file and it works. Hope to be helpful to someone newly here.

Could you please show how did you replace distributed.py with APEX distributed.py file? I replaced it, after that I got 

from ..multi_tensor_apply import multi_tensor_applier
Import Error.

Finally I tried to copy the multi_tensor_apply folder from APEX to my repo, but it still not working. The Error is

Traceback (most recent call last):
  File "train.py", line 289, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 162, in train
    init_distributed(hparams, n_gpus, rank, group_name)
  File "train.py", line 37, in init_distributed
    world_size=n_gpus, rank=rank, group_name=group_name)
  File "/mnt/home/jupyter_dir/my_env1/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 500, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/mnt/home/jupyter_dir/my_env1/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 138, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use

and it hangs and never go to the training step.
