### ISSUE TITLE
The benefits of filelists randomly shuffling?

### ISSUE THREAD

**Issue by a8568730** [NVIDIA/tacotron2#65]
Hi,
Thank you for this great project, and we're trying to implement a open-source Taiwanese text-to-speech synthesis service with this project.

We found the three lists (train, test, val) in `filelists/` is randomly shuffling.
For example, the first few lines in `ljs_audio_text_train_filelist.txt` is
```
DUMMY/LJ001-0003.wav|...
...
DUMMY/LJ001-0001.wav|...
...
DUMMY/LJ001-0002.wav|...
...
```
Rather in order
```
DUMMY/LJ001-0001.wav|...
DUMMY/LJ001-0002.wav|...
DUMMY/LJ001-0003.wav|...
...
```
We wonder the reason of shuffling, thinking if we need to shuffle our corpus list too.
Is there any benefits to shuffle?

**Comment by gsoul** [comment]
The idea behind shuffling is to not converge too early to the local minima and let model generalize better.

**Comment by a8568730** [comment]
Ooh I see. :D
Some parts of the corpus may contains some similar sentence patterns or same words next to each lines, like talking about a particular topic.
With shuffling, we disrupt all the speech patterns in the corpus to avoid from the local minima.
