### ISSUE TITLE
Audio Recording for Dataset

### ISSUE THREAD

**Issue by jferrer21** [NVIDIA/tacotron2#70]
Would 10 hours of audio recording be enough to achieve "state of the art quality"?

How long will it take to train in an AWS machine with one v100 GPU?

**Comment by rafaelvalle** [comment]
It's possible to train a model even with 1 hour of data but it's vocabulary will be extremely limited, etc. 

With a V100 it should take less than a day to train Tacotron 2, specially with the model we're about to release. Note that you will need the wavenet decoder to achieve state-of-the-art **audio quality** .

**Comment by vikrantsharma7** [comment]
@rafaelvalle Can you please elaborate the kind of fine tuning that would be required for such small datasets (1-5 hrs)?
A smaller embedding size, encoder dims, attention dims?
For Tacotron2 as well as WaveGlow
