### ISSUE TITLE
Please explain the Setup again elaborately

### ISSUE THREAD

**Issue by deadskull7** [NVIDIA/tacotron2#73]
This is to the contributors of this repository and any other 3rd person who knows how to setup the repo. in one's machine till fully working and result stage. I am having some problem in 4th part of setup. Please help me out. Thanks in advance.

```
Update .wav paths: sed -i -- 's,DUMMY,ljs_dataset_folder/wavs,g' filelists/*.txt

    Alternatively, set load_mel_from_disk=True in hparams.py and update mel-spectrogram paths

```

Its coming like ` 'sed' is not recognized as an internal or external command, operable program or batch file.`

**Comment by deadskull7** [comment]
My Bad .... Its done.

**Comment by EuphoriaCelestial** [comment]
please explain it again, I dont know what need to be changed accordingly

**Comment by CookiePPP** [comment]
@EuphoriaCelestial 
the command will replace all `DUMMY` lines inside the filelists folder with `ljs_dataset_folder/wavs`.

Replace **`ljs_dataset_folder`** inside
```
sed -i -- 's,DUMMY,ljs_dataset_folder/wavs,g' filelists/*.txt
```
with the path to your `LJSpeech-1.1` directory.

**Comment by EuphoriaCelestial** [comment]
@CookiePPP thank you! since the command only correct the file path in the filelists folder, I have done it using Text editor on Ubuntu. It will work right? No issue later on?

**Comment by CookiePPP** [comment]
@EuphoriaCelestial 
That should work yes.
