### ISSUE TITLE
Pre-emphasis is important on audio signal processing

### ISSUE THREAD

**Issue by begeekmyfriend** [NVIDIA/tacotron2#75]
Here is the difference about adding pre-emphasis before STFT and inverted pre-emphasis after G&L outputs or not. Why not consider adding pre-emphasis into audio processing?
[preemphasis_or_not.zip](https://github.com/NVIDIA/tacotron2/files/2313813/preemphasis_or_not.zip)

![non-preemphasis](https://user-images.githubusercontent.com/6031938/44517442-4ab1c800-a6fa-11e8-8883-0dc5ce90c421.png)
![preemphasis](https://user-images.githubusercontent.com/6031938/44517444-4be2f500-a6fa-11e8-99aa-36bc3af1eb44.png)

**Comment by rafaelvalle** [comment]
We're providing a clean implementation. Thank you for raising this.
