### ISSUE TITLE
Typo in comment for get_alignment_energies() in model.py

### ISSUE THREAD

**Issue by hitrefresh** [NVIDIA/tacotron2#79]
@rafaelvalle 
https://github.com/NVIDIA/tacotron2/blob/master/model.py 
`Line 48:       query: decoder output (batch, n_mel_channels * n_frames_per_step)`

Here `query` is the hidden state of Attention RNN, which should have size `(batch, attention_rnn_dim)`?

**Comment by rafaelvalle** [comment]
The code has been updated. Please send a PR if the problem remains.
