### ISSUE TITLE
CUDA required for inference

### ISSUE THREAD

**Issue by splitice** [NVIDIA/tacotron2#81]
Does anyone know if CUDA / a NVIDIA GPU is required for inference with this model?

**Comment by pfriesch** [comment]
yes

**Comment by splitice** [comment]
@pfriesch Thanks.

Hoping to get this to run at near real time (within 2-3x less than real time would be acceptable) on an embedded system. Of course with a model trained on a GPU cluster.

Do you happen to know roughly what the memory usage is like with the model loaded for inference? Within 300-400mb?

**Comment by pfriesch** [comment]
How do you plan to synthesize from spectrogram -> raw audio?

**Comment by splitice** [comment]
First step is concept validation which is why I was going with something simple. I'll take a look at that though.

**Comment by rafaelvalle** [comment]
Please take a look at our Inference demo for guidance on how to synthesize from mel to raw audio.
