### ISSUE TITLE
No gain using FP16 on a GV100

### ISSUE THREAD

**Issue by macarbonneau** [NVIDIA/tacotron2#82]
Hello!
        Thank you for the nice implementation. I was wondering if you have tried to run the tacotron on a GV100 ...and if you did if you got a speed-up. 

My baseline is a 1080Ti and so far, I get a gain only because I can train with bigger batches. I run in the FP16 mode to use the tensor core and yet it does not go faster. In fact, it goes slightly slower than with FP32. From what I saw from the implementation, all I have to do is set fp16 to true. Am I missing something?

Thank you in advance

**Comment by rafaelvalle** [comment]
That is similar to what we currently perceive. We're working on improving it.

**Comment by lee-bin** [comment]
Any update on this?
