### ISSUE TITLE
How to synthesize long sentences?

### ISSUE THREAD

**Issue by hadiasheri** [NVIDIA/tacotron2#84]
I've trained tacotron2 with LJSpeech for about 200K iterations.
The synthesized speech is great for sentences with maximum length of about 50 words.
However, when you feed a long sentence ( e.g length~100), it fails to produce acceptable speech because some parts of the sentences are missing or pronounced awfully.
Do you have any experiences to synthesize sentences of arbitrary length with tacotron?

**Comment by rafaelvalle** [comment]
A quick solution is to break the input into multiple sentences.
