### ISSUE TITLE
can't lanch RuntimeError

### ISSUE THREAD

**Issue by xinge333** [NVIDIA/tacotron2#9]
why I run train.py after I prepared data,  it can't work. an issue called OOM?

File "train.py", line 79, in load_model
    model = Tacotron2(hparams).cuda()
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCTensorRandom.cu:25

**Comment by rafaelvalle** [comment]
Make sure you batch size fits the GPU by watching GPU memory consumption with the command `nvidia-smi`. If it doesn't decrease it accordingly.

**Comment by syoyo** [comment]
@xinge333 FYI it looks batch size `32` works well for GTX 1080 Ti(consumes 10 GB out of 11 GB mem. and `train` could run at least for 24 hours)

**Comment by xinge333** [comment]
ok , it has been solver after I assign  gpu:1; thanks ! my batch size is 32 ,it's ok. I forget to set CUDA_VISIBLE_DEVICES=gpu_id,  now it fixed.
