### ISSUE TITLE
No module named 'glow_old'

### ISSUE THREAD

**Issue by williamFalcon** [NVIDIA/tacotron2#97]
When trying to load waveglow like:  

```
        waveglow_path = self.hparams.waveglow_path
        self.waveglow = torch.load(waveglow_path)['model']
```   

I get this error:   

```

result = unpickler.load()
ModuleNotFoundError: No module named 'glow_old'
```

**Comment by nanma** [comment]
@williamFalcon Have you Initialized the submodule of waveglow?

**Comment by williamFalcon** [comment]
Yup, that fixed it. However 2 problems still remain:

1.  Weights are for GPU only. Saving state dict is probably a better approach.
2. Pytorch 1.0 has an issue with padded rnns... so can't use the waveglow inference + this code in the same environment

**Comment by peter05010402** [comment]
@williamFalcon  How do you solve the problem "ModuleNotFoundError: No module named 'glow_old'"?

**Comment by pierrewessman** [comment]
If anyone gets here wondering how to solve the initialization of the submodule here is how you do it:
git submodule init; git submodule update
